# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

import importlib.util
import subprocess
import sys

REQUIRED = {
    "geopandas": "geopandas",
    "shapely": "shapely",
    "networkx": "networkx",
    "osmnx": "osmnx",
    "partridge": "partridge",
    "pulp": "pulp",
    "scipy": "scipy",
    "pyarrow": "pyarrow",
    "pyogrio": "pyogrio",
    "geopy": "geopy",
    "pyproj": "pyproj",
}

def _missing_packages():
    return [pip_name for mod_name, pip_name in REQUIRED.items()
            if importlib.util.find_spec(mod_name) is None]
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MobilityHubPlugin class from file MobilityHubPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    missing = _missing_packages()
    if missing:
        from qgis.PyQt.QtWidgets import QMessageBox
        reply = QMessageBox.question(
            None, "MobilityHubPlugin — Dépendances manquantes",
            "Les bibliothèques Python suivantes sont requises et absentes :\n\n"
            f"{', '.join(missing)}\n\n"
            "Voulez-vous les installer automatiquement maintenant "
            "(nécessite un redémarrage de QGIS ensuite) ?",
        )
        
    from .mobilityhubplugin import MobilityHubPluginPlugin
    return MobilityHubPluginPlugin()

