# -*- coding: utf-8 -*-
"""
Created on Thu Aug 27 14:13:17 2026

@author: eleonore.lagourgue
"""

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication,QVariant
from qgis.core import *
from qgis.utils import *
from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing
from mobilityhubplugin.conversions import ( 
                         gdf_to_qgsfields,
                         write_gdf_to_sink,
                         gdf_from_layer_arrow,
                         gdf_geom_to_qgs_wkbtype)

import networkx as nx
import osmnx as ox
import numpy as np
from scipy.stats import gaussian_kde
import geopandas as gpd
from skimage.feature import peak_local_max


class CreaHubsPot(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    NATURE = "NATURE"
    RESEAU = "RESEAU"
    NODES = "NODES"
    POP = "POP"
    IDPOP = "IDPOP"
    SERVICES = "SERVICES"
    IDHUB = "IDHUB"
    ZONE_ACT = "ZONE_ACT"
    IDDEST ="IDDEST"
    MODE = "MODE"
    WEIGHT = "WEIGHT"
    MATRIX = "MATRIX"
   
    
    def createInstance(self):
        return CreaHubsPot()

    def name(self):
        return "matrice_temps"

    def displayName(self):
        return "Crée une matrice de temps de trajet"

    def group(self):
        return "Analyse réseau"
    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'analyse_reseau'
    
    
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile( 
                self.REP_GTFS,
                self.tr('zip GTFS'),
                QgsProcessingParameterFile.File,
                extension='zip',
                optional=False
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU, 
                "Lignes du réseau (lignes)",
                [QgsProcessing.SourceType.TypeVectorLine]))
        self.addParameter(
            QgsProcessingParameterNumber(
                self.TOLERANCE, 
                self.tr("Tolérance topologique (en mètres)"), defaultValue=-1))
        
        self.addParameter(
            QgsProcessingParameterField(
                self.IDDEST, 
                "Colonne de nature de la route",
                parentLayerParameterName=self.RESEAU,
                optional = True))
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.ZONE_ACT, 
                "Zones d'activité et/ ou commerciale",
                [QgsProcessing.SourceType.TypeVectorPolygon],
                optional = True))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.SERVICES, 
                "Points de services/points d'intérêt (si pas polygone de zone d'activité)",
                [QgsProcessing.SourceType.TypeVectorPoint],
                optional = True))
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.POP, 
                "Données de population",
                [QgsProcessing.SourceType.TypeVectorPolygon],
                optional = True))
    
        
        
        
    def processAlgorithm(self, parameters, context, feedback):
        
         
         
        """
        Here is where the processing itself takes place.
        """
        lignes_layer = self.parameterAsVectorLayer(parameters, self.RESEAU, context)#QgsProcessingFeatureSource
        nodes_layer = self.parameterAsVectorLayer(parameters, self.NODES, context)#QgsProcessingFeatureSource
    
        services_layer = self.parameterAsVectorLayer(parameters, self.SERVICES, context)#QgsProcessingFeatureSource
        services_layer = self.parameterAsVectorLayer(parameters, self.ZONE_ACT, context)#QgsProcessingFeatureSource
        pop_layer = self.parameterAsVectorLayer(parameters, self.POP, context)
        # =============================================================================
        #        Calcul centralité des routes  
        # =============================================================================
        edges = gdf_from_layer_arrow(lignes_layer)
        nodes = gdf_from_layer_arrow(nodes_layer)
        edges = gdf_from_layer_arrow(lignes_layer)
        nodes = nodes.set_index("osmid")
        edges = edges.set_index(["u", "v", "key"])
        G = ox.graph_from_gdfs(nodes, edges)
        G_undirected = ox.convert.to_undirected(G)
    
        bc = nx.betweenness_centrality(G_undirected, weight="length", normalized=True)
        nx.set_node_attributes(G, bc, "betweenness")
         
         
        # =============================================================================
        #          Calcul concentration des services
        # =============================================================================
        services = gdf_from_layer_arrow(services_layer)
        x = services.geometry.x
        y = services.geometry.y
        xy = np.vstack([x, y])
        kde = gaussian_kde(xy, bw_method=0.15)
        
        xmin, ymin, xmax, ymax = services.total_bounds
        margin_x = (xmax - xmin) * 0.05
        margin_y = (ymax - ymin) * 0.05
        xmin, xmax = xmin - margin_x, xmax + margin_x
        ymin, ymax = ymin - margin_y, ymax + margin_y
        xx, yy = np.mgrid[xmin:xmax:complex(grid_size), ymin:ymax:complex(grid_size)]
        positions = np.vstack([xx.ravel(), yy.ravel()])
        
        print("Calcul du KDE sur la grille (peut prendre quelques secondes)...")
        density = np.reshape(kde(positions), xx.shape)
        cell_size_x = (xmax - xmin) / grid_size
        min_distance_px = max(1, int(min_distance_m / cell_size_x))
        
        relative_threshold = 0.15

        coordinates = peak_local_max(
            density,
            min_distance=min_distance_px,
            threshold_rel=relative_threshold,
            )
        peaks = []
        for row, col in coordinates:
            
            x = xx[row, col]
            y = yy[row, col]
            peaks.append({
               "geometry": Point(x, y),
               "density": float(density[row, col])})
       
        gdf_peaks = gpd.GeoDataFrame(peaks)
        # Trier par intensité décroissante (le centre-ville principal en premier)
        gdf_peaks = gdf_peaks.sort_values("density", ascending=False).reset_index(drop=True)
        gdf_peaks["rang"] = gdf_peaks.index + 1
        
        x = gdf_peaks.geometry.x
        y = gdf_peaks.geometry.y 
        
        gdf_peaks["ne_idx"] = ox.nearest_edges(G, x,y) #renvoie les 3
       
        print(f"{len(gdf_peaks)} pic(s) de densité détecté(s) = centre(s)-ville(s) candidat(s).")
        cand =[]
        for cluster in gdf_peaks.iterrows():
            u,v,key = cluster["ne_idx"]
            edge_data = G.edges[u,v,key]
            if cluster["rang"] >6 and edge_data["betweenness"] >5:
                cand.append(cluster)
        
        cand_gdf = gpd.GeoDataFrame(cand, geometry ="geometry", crs = gdf_peaks.crs)   
        
        crs = lignes_layer.crs()  # on réutilise le CRS de la couche d'entrée

        # --- Sink lignes ---
        lines_fields = gdf_to_qgsfields(cand_gdf)
        lines_wkbtype = gdf_geom_to_qgs_wkbtype(cand_gdf)
        (sink_lignes, dest_id_lignes) = self.parameterAsSink(
            parameters, self.LIGNES, context,
            lines_fields, lines_wkbtype, crs
        )
        write_gdf_to_sink(cand_gdf, sink_lignes)
    
       
        return {self.OUTPUT: dest_id_lignes}
         
         
         
         

         




         

         
         
         
         
         
         
         
         
         