"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFile,
    QgsFeatureSink,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant

from .optimization_model import ProblemData, solve_poi_model
from .itinerary_io import build_poi_problem_data


class LocateHubsPOIAlgorithm(QgsProcessingAlgorithm):
    NODES = "NODES"
    ITINERAIRES = "ITINERAIRES"
    HUBS = "HUBS"
    POIS = "POIS"
    BUDGET = "BUDGET"
    THRESHOLD = "THRESHOLD"
    OUTPUT = "OUTPUT"

    def createInstance(self):
        return LocateHubsPOIAlgorithm()

    def name(self):
        return "locate_hubs_poi"

    def displayName(self):
        return "Localiser les hubs (accessibilité POI)"

    def group(self):
        return "Localisateur de Hubs"

    def groupId(self):
        return "mobility_hub"

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFeatureSource(self.NODES, "Nœuds de population (points)"))
        self.addParameter(QgsProcessingParameterFeatureSource(self.HUBS, "Hubs candidats (points)"))
        self.addParameter(QgsProcessingParameterFeatureSource(self.POIS, "Points d'intérêt (points, avec champ 'category')"))
        self.addParameter(QgsProcessingParameterFile(self.ITINERAIRES, "Itinéraires potentiels"))
        self.addParameter(QgsProcessingParameterNumber(self.BUDGET, "Budget (€)", defaultValue=150000))
        self.addParameter(QgsProcessingParameterNumber(self.THRESHOLD, "Seuil de temps de trajet (min)", defaultValue=30))
        self.addParameter(QgsProcessingParameterFeatureSink(self.OUTPUT, "Hubs sélectionnés"))

    def processAlgorithm(self, parameters, context, feedback):
        nodes_src = self.parameterAsSource(parameters, self.NODES, context)#QgsProcessingFeatureSource
        hubs_src = self.parameterAsSource(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        pois_src = self.parameterAsSource(parameters, self.POIS, context)#QgsProcessingFeatureSource
        itineraries_src = self.parameterAsSource(parameters, self.ITINERAIRES, context)
        budget = self.parameterAsDouble(parameters, self.BUDGET, context)#float

        feedback.pushInfo("Construction des itinéraires potentiels (routage + élimination des dominés)...")
        
        #modes : à récupérer selon itineraires.mod_seq unique() 
        data = build_poi_problem_data(
            nodes_src, hubs_src, itineraries_src,
            poi_categories=["pharmacy", "hospital", "supermarket"],
            travel_time_threshold={"pharmacy": 30, "hospital": 30, "supermarket": 30},
            modes=["pt", "bs", "cs"],
            fixed_cost_hub=1000.0,
            fixed_cost_mode={"bs": 300.0, "cs": 7500.0, "pt": 0.0},
            budget=budget,
        )

        feedback.pushInfo(f"{len(data.itineraries)} itinéraires potentiels générés. Résolution du MIP...")
        result = solve_poi_model(data, time_limit_s=300)
        feedback.pushInfo(f"Statut : {result['status']} — accessibilité obtenue : {result['objective']:.3f}")

        fields = QgsFields()
        fields.append(QgsField("hub_id", QVariant.String))
        fields.append(QgsField("mode", QVariant.String))

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context, fields, QgsWkbTypes.Point, hubs_src.sourceCrs()
        )

        hub_features = {f["id"]: f for f in hubs_src.getFeatures()}
        for (hub_id, mode) in result["hubs"]:
            src_feat = hub_features.get(hub_id)
            if src_feat is None:
                continue
            out_feat = QgsFeature(fields)
            out_feat.setGeometry(src_feat.geometry())
            out_feat.setAttributes([hub_id, mode])
            sink.addFeature(out_feat, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}
