# -*- coding: utf-8 -*-
"""
Created on Fri Jul 17 12:11:49 2026

@author: eleonore.lagourgue
"""

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFile,
    QgsFeatureSink,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant

import pandas as pd
class BuildItineraries(QgsProcessingAlgorithm):
    POP = "POP"
    HUBS = "HUBS"
    DESTINATION = "DESTINATION"
    MATRIXPT = "MATRIXPT"
    MATRIXCAR ="MATRIXCAR"
    MATRIXBIKE = "MATRIXBIKE"
    MATRIXWALK = "MATRIXWALK"
    BUDGET = "BUDGET"
    THRESHOLD = "THRESHOLD"
    OUTPUT = "OUTPUT"

    def createInstance(self):
        return BuildItineraries()

    def name(self):
        return "build_potential_itineraries"

    def displayName(self):
        return "Construire les itinéraires potentiels"

    def group(self):
        return "Analyse réseau"

    def groupId(self):
        return "analyse_reseau"
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFeatureSource(self.POP, 
                                                              "Nœuds de population (points)"))
        self.addParameter(QgsProcessingParameterFeatureSource(self.HUBS, 
                                                              "Hubs candidats (points)"))
        self.addParameter(QgsProcessingParameterFeatureSource(self.DESTINATION, 
                                                              "Destinations (si différent de nœuds de population) "))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXPT, 
                                                              "Matrice de temps transportS en commun",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXCAR, 
                                                              "Matrice de temps voiture",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXBIKE, 
                                                              "Matrice de temps vélo",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXWALK, 
                                                              "Matrice de temps marche",
                                                              extension = "csv"))
    def processAlgorithm(self, parameters, context, feedback):
        nodes_src = self.parameterAsSource(parameters, self.POP, context)#QgsProcessingFeatureSource
        hubs_src = self.parameterAsSource(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        dest_src = self.parameterAsSource(parameters, self.DESTINATION, context)#QgsProcessingFeatureSource
        matrix_pt_path = self.parameterAsFile(parameters, self.MATRIXPT, context)
        matrix_b_path = self.parameterAsFile(parameters, self.MATRIXBIKE, context)
        matrix_car_path = self.parameterAsFile(parameters, self.MATRIXCAR, context)
        matrix_w_path = self.parameterAsFile(parameters, self.MATRIXWALK, context)


        feedback.pushInfo("Construction des itinéraires potentiels (routage + élimination des dominés)...")
        matrix_pt = pd.read_csv(matrix_pt_path)
        matrix_bike = pd.read_csv(matrix_b_path)
        matrix_car = pd.read_csv(matrix_car_path)
        matrix_walk = pd.read_csv(matrix_w_path)

        self.itineraries(matrix_pt,matrix_car, matrix_bike, matrix_walk)
        data =...
        feedback.pushInfo(f"{len(data.itineraries)} itinéraires potentiels générés. Résolution du MIP...")
    def itineraries(matrix_pt, matrix_car, matrix_bike, matrix_walk):
        
        pass
    def get_useful_hubs(i, j, hubs_potentiels, 
                        mat_pt, mat_car, t_pt, t_max, min_improvement):
        pass





