# -*- coding: utf-8 -*-
"""
Created on Fri Jul 17 12:11:49 2026

@author: eleonore.lagourgue
"""

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFile,
    QgsProcessingParameterField,
    QgsFeatureSink,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant

import pandas as pd
import numpy as np
from dataclasses import dataclass, field
from collections import defaultdict


from .optimization_model import WorkplaceProblemData, Itinerary, WorkplaceItinerary




class BuildItinerariesWP(QgsProcessingAlgorithm):
    POP = "POP"
    IDPOP = "IDPOP"
    HUBS = "HUBS"
    IDHUB = "IDHUB"
    DESTINATION = "DESTINATION"
    IDDEST ="IDDEST"
    MATRIXPT = "MATRIXPT"
    MATRIXCAR ="MATRIXCAR"
    MATRIXBIKE = "MATRIXBIKE"
    MATRIXWALK = "MATRIXWALK"
    BUDGET = "BUDGET"
    THRESHOLD = "THRESHOLD"
    OUTPUT = "OUTPUT"

    def createInstance(self):
        return BuildItinerariesWP()

    def name(self):
        return "build_potential_itineraries"

    def displayName(self):
        return "Construire les itinéraires potentiels (version workplace)"

    def group(self):
        return "Analyse réseau"

    def groupId(self):
        return "analyse_reseau"
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFeatureSource(self.POP, 
                                                              "Nœuds de population (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDPOP, 
                                                      "Colonne id pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(QgsProcessingParameterFeatureSource(self.HUBS,
                                                              "Hubs candidats (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDHUB, 
                                                      "Colonne id pour la couche des hubs",
                                                      parentLayerParameterName=self.HUBS))
        
        self.addParameter(QgsProcessingParameterFeatureSource(self.DESTINATION,
                                                              "Destinations (si différent de nœuds de population) ",
                                                              [QgsProcessing.SourceType.TypeVectorPoint],
                                                              optional = True))
                                                      
        self.addParameter(QgsProcessingParameterField(self.IDDEST, 
                                              "Colonne id pour la couche de destination",
                                              parentLayerParameterName=self.DESTINATION,
                                              optional = True))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXPT, 
                                                              "Matrice de temps transportS en commun",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXCAR, 
                                                              "Matrice de temps voiture",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXBIKE, 
                                                              "Matrice de temps vélo",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXWALK, 
                                                              "Matrice de temps marche",
                                                              extension = "csv"))
    def processAlgorithm(self, parameters, context, feedback):
        nodes_src = self.parameterAsSource(parameters, self.POP, context)#QgsProcessingFeatureSource
        hubs_src = self.parameterAsSource(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        dest_src = self.parameterAsSource(parameters, self.DESTINATION, context)#QgsProcessingFeatureSource
        matrix_pt_path = self.parameterAsFile(parameters, self.MATRIXPT, context)
        matrix_b_path = self.parameterAsFile(parameters, self.MATRIXBIKE, context)
        matrix_car_path = self.parameterAsFile(parameters, self.MATRIXCAR, context)
        matrix_w_path = self.parameterAsFile(parameters, self.MATRIXWALK, context)


        feedback.pushInfo("Construction des itinéraires potentiels (routage + élimination des dominés)...")
        matrix_pt = pd.read_csv(matrix_pt_path)
        matrix_bike = pd.read_csv(matrix_b_path)
        matrix_car = pd.read_csv(matrix_car_path)
        matrix_walk = pd.read_csv(matrix_w_path)

        self.itineraries(matrix_pt,matrix_car, matrix_bike, matrix_walk)
        data =...
        feedback.pushInfo(f"{len(data.itineraries)} itinéraires potentiels générés. Résolution du MIP...")
    def itineraries(origin, hubs,matrix_pt, matrix_car, matrix_bike, 
                    matrix_walk, dest = None, max_ratio_vs_car=3.0,
                    min_improvement=0.10):
        itineraries = []
        iid = 0 #compteur pour créer l'id de chaque itinéraire
        
        for i, orig in origin.items():
            for j, dest in origin.items():
                if orig == dest:
                    continue

                t_car = matrix_car.loc[i, j] #temps en voiture
                t_pt  = matrix_pt.loc[i, j] #temps de comparaison
                if t_car == np.inf or t_pt == np.inf:
                    continue
                t_max = min(t_pt, max_ratio_vs_car * t_car)
                
                #On ajoute toujours le temps en TC
                itineraries.append(Itinerary(
                    origin=i, destination=j,
                    mode_seq=["pt"], hubs_required=[],
                    travel_time=t_pt, itinerary_id=iid
                ))
                iid += 1
                
        WorkplaceProblemData(
            commuting_volume=commuting_volume,
            hub_locations=[f["id"] for f in hubs_src.getFeatures()],
            modes=list(modes),
            itineraries=itineraries,
            fixed_cost_hub=1000.0,          # cf. Table 2 (c^F)
            fixed_cost_mode={"bs": 300.0, "cs": 7500.0},  # cf. Table 2
            budget=budget,
        )
        pass
    def get_useful_hubs(i, j, hubs_potentiels, 
                        mat_pt, mat_car, t_pt, t_max, min_improvement):
        """
        Ne retourne que les hubs h tels que :
        - PT(i vers h) + CAR(h vers j) < t_pt * (1 - min_improvement)
        - ou CAR(i vers h) + PT(h vers j) < t_pt * (1 - min_improvement)
        Évite d'énumérer tous les hubs pour chaque paire O-D.
        """
        useful = []
        for hub_id in hubs_potentiels:
            print(hub_id)
             
            t1 = mat_pt[i][hub_id] + TRANSFER_TIME + mat_car[hub_id][j]
            t2 = mat_car[i][hub_id] + TRANSFER_TIME + mat_pt[hub_id][j]
            
            if (t1 < t_pt * (1 - min_improvement) and t1 < t_max) or \
               (t2 < t_pt * (1 - min_improvement) and t2 < t_max) :
                useful.append(hub_id)
        return useful
    def elimination_itineraires_domines(itineraires):
        by_od = defaultdict(list)
        for it in itineraires:
            by_od[(it.origin, it.destination)].append(it)
            #Construit dictionnaire avec comme clé origine& destination

        kept = []
        for od, itis in by_od.items():
            its_sorted = itis.sort_values(by = ["travel_time"])
            non_dominated = []
            for cand in its_sorted:
                dominated = False
                req_c = set(cand.hubs_required)
                for better in non_dominated:
                    req_b = set(better.hubs_required)
                    # cand dominé si ses requirements sont un surensemble de ceux de better
                    # ET better est plus rapide (garanti par le tri i.e. sorted)
                    if req_b.issubset(req_c):
                        dominated = True
                        break
                if not dominated:
                    non_dominated.append(cand)
            kept.extend(non_dominated)

        return kept





