# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessing,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFile,
    QgsProcessingParameterFileDestination,
    QgsVectorLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterEnum,
    QgsProcessingParameterField,
    QgsProcessingOutputString,
    QgsProcessingOutputLayerDefinition,
    QgsProcessingParameterString,
    QgsProcessingParameterFeatureSink,
    QgsFeature, QgsGeometry, QgsFields, QgsField,
    QgsWkbTypes, QgsCoordinateReferenceSystem,
)
from qgis.analysis import QgsVectorLayerDirector
from qgis.PyQt.QtCore import QVariant, QCoreApplication




class MergeGTFS(QgsProcessingAlgorithm):

    INPUT = "INPUT"
    OUTPUT_ZIP = "OUTPUT_ZIP"
    def __init__(self):
        super().__init__()
    def name(self): return "merge_gtfs"
    def displayName(self): return "Concaténer des réseaux de transports en commun"
    def createInstance(self): return MergeGTFS()
    def group(self): return "Réseau"
    def groupId(self): return "reseau"
    def tr(self, string):
        return QCoreApplication.translate('MergeGTFS', string)
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterFile( 
                self.REP_GTFS,
                self.tr('zip GTFS'),
                behavior= QgsProcessingParameterFile.Folder,
                optional=False
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_PATH,
                self.tr('Chemin de sortie'),
                fileFilter = "zip",
                optional=False

                
            )
        )




