# -*- coding: utf-8 -*-
"""
Created on Thu Jul 16 14:46:46 2026

@author: eleonore.lagourgue
"""
"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication,QVariant
from qgis.core import *
from qgis.utils import *
# from qgis.core import (QgsProcessing,
#                        QgsFeatureSink,
#                        QgsProcessingAlgorithm,
#                        QgsProcessingParameterFeatureSource,
#                        QgsProcessingParameterFeatureSink,
#                        QgsProcessingParameterNumber,
#                        QgsProcessingParameterBoolean,
#                        QgsProcessingParameterString,
#                        QgsProcessingParameterExtent,
#                        QgsProcessingParameterField,
#                        QgsProcessingParameterExpression,
#                        QgsProcessingParameterFileDestination,
#                        QgsSpatialIndex,
#                        QgsGeometry,
#                        QgsFeature,
#                        QgsField,
#                        QgsFields,
#                        QgsCoordinateTransform,
#                        QgsCoordinateReferenceSystem
#                        )

from qgis import processing

from mobilityhubplugin.conversions import ( 
                         gdf_geom_to_qgs_wkbtype,
                         gdf_to_qgsfields,
                         write_gdf_to_sink,
                         gdf_from_layer_arrow)
import osmnx as ox
import networkx as nx
import pandas as pd
import numpy as np
from scipy.sparse.csgraph import dijkstra as scipy_dijkstra
import os


def nearest_node(G, lat, lon):
    return ox.nearest_nodes(G, lon, lat)

def add_nearest_node(layer, G, field_name, colonne_id,feedback=None):
    nom_champs = [f.name() for f in layer.fields()]

    if not layer.isEditable():
        layer.startEditing()

    
    if (field_name not in nom_champs):
        layer.dataProvider().addAttributes([QgsField(field_name,QVariant.Int)])
    
    layer.updateFields()
    idx = layer.fields().indexFromName(field_name)
    
    feats = list(layer.getFeatures())
    if not feats:
        layer.commitChanges()
        return {}

        
        
    ids = []
    xs = []  # longitude
    ys = []  # latitude
    seen_ids = set()
    for feat in feats:
        code = feat[colonne_id]
        if code in seen_ids and feedback:
            feedback.pushWarning(
                f"Identifiant '{code}' dupliqué dans la colonne '{colonne_id}' "
                f"de la couche '{layer.name()}' : les doublons s'écraseront."
            )
        seen_ids.add(code)
        pt = feat.geometry().asPoint()
        ids.append(code)
        xs.append(pt.x())  # X = longitude
        ys.append(pt.y())  # Y = latitude
 
    # Un seul appel vectorisé : X = longitudes, Y = latitudes (ordre correct)
    nearest = ox.nearest_nodes(G, X=xs, Y=ys)
    if np.isscalar(nearest):
        nearest = [nearest]
 
    values = {}
    for feat, code, node in zip(feats, ids, nearest):
        values[code] = node
        layer.changeAttributeValue(feat.id(), idx, int(node))
 
    ok = layer.commitChanges()
    if not ok and feedback:
        feedback.pushWarning(
            f"Impossible d'enregistrer les modifications sur la couche '{layer.name()}'."
        )
    return values



def lat_lon(layer):
    #A supprimer ?
    nom_champs=[]
    layer.startEditing()
    for i in layer.fields():
        nom_champs.append(i.name())
    if ("lon" not in nom_champs):
        layer.dataProvider().addAttributes([QgsField("lon",QVariant.Int)])
    if ("lat" not in nom_champs):
        layer.dataProvider().addAttributes([QgsField("lat",QVariant.Int)])
  
    layer.updateFields()
    layer.commitChanges()
    return layer

def build_time_matrix(G, all_nodes, weight, feedback=None, batch_size=200):
    """
    Calcule la matrice temps (en minutes) entre tous les nœuds de all_nodes,
    en une seule passe via scipy (Dijkstra multi-source, code compilé),
    au lieu d'un Dijkstra networkx par nœud source.
 
    all_nodes : dict {label: osmid}
    """
    if feedback:
        feedback.pushInfo("Conversion du MultiDiGraph en DiGraph (poids minimal conservé)...")
    
    DG = ox.convert.to_digraph(G, weight=weight)
    
    
    node_list = list(DG.nodes())
    node_index = {n: i for i, n in enumerate(node_list)}
    
    keys = list(all_nodes.keys())
    osm_ids = [all_nodes[k] for k in keys]
    target_indices = np.array([node_index[n] for n in osm_ids])
    
    n = len(target_indices)
    result = np.full((n, n), np.inf, dtype=np.float32)  # float32 pour limiter la mémoire
    
    if feedback:
        feedback.pushInfo("Construction de la matrice creuse du réseau...")
    A = nx.to_scipy_sparse_array(DG, nodelist=node_list, weight=weight, format="csr")
    
    for start in range(0, n, batch_size):
        end = min(start + batch_size, n)
        batch_source_idx = target_indices[start:end]

        feedback.pushInfo(f"Calcul Dijkstra {start}-{end} / {n} ...")

        # dist_batch shape: (batch_size, n_total_nodes_du_graphe)
        dist_batch = scipy_dijkstra(
            csgraph=A,
            directed=True,
            indices=batch_source_idx,
        )

        # On ne garde QUE les colonnes correspondant à nos nœuds d'intérêt
        result[start:end, :] = dist_batch[:, target_indices]

        del dist_batch  # libère la mémoire immédiatement

        if feedback.isCanceled():
            break

 
    
    result = result / 60.0  # secondes -> minutes
    matrix = pd.DataFrame(result, index=keys, columns=keys)
    matrix.index.name = "origine"
    return matrix


class MatriceTemps(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    NODES = "NODES"
    RESEAU = "RESEAU"
    POP = "POP"
    IDPOP = "IDPOP"
    HUBS = "HUBS"
    IDHUB = "IDHUB"
    DESTINATION = "DESTINATION"
    IDDEST ="IDDEST"
    MODE = "MODE"
    WEIGHT = "WEIGHT"
    MATRIX = "MATRIX"
   
    
    def createInstance(self):
        return MatriceTemps()

    def name(self):
        return "matrice_temps"

    def displayName(self):
        return "Crée une matrice de temps de trajet"

    def group(self):
        return "Analyse réseau"

    def groupId(self):
        return "analyse_reseau"
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFeatureSource(self.NODES, 
                                                              "Nœuds du réseau (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterFeatureSource(self.RESEAU, 
                                                              "Lignes du réseau (lignes)",
                                                              [QgsProcessing.SourceType.TypeVectorLine]))

        self.addParameter(QgsProcessingParameterField(self.WEIGHT, 
                                                      "Colonne poids",
                                                      parentLayerParameterName=self.RESEAU))
        
        self.addParameter(QgsProcessingParameterFeatureSource(self.POP, 
                                                              "Nœuds de population (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDPOP, 
                                                      "Colonne id pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(QgsProcessingParameterFeatureSource(self.HUBS,
                                                              "Hubs candidats (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDHUB, 
                                                      "Colonne id pour la couche des hubs",
                                                      parentLayerParameterName=self.HUBS))
        
        self.addParameter(
        QgsProcessingParameterEnum(
        self.MODE,
        'Choisir un mode de déplacement',
        options=['Voiture', 'Piéton', 'Vélo','Transport en commun'],
        allowMultiple=False,
        defaultValue=0,   # index par défaut (0 = premier élément)
        optional=False    # <-- rend le paramètre obligatoire
            )
        )
        
        
        #----------Paramètres optionnels#----------
        self.addParameter(QgsProcessingParameterFeatureSource(self.DESTINATION,
                                                              "Destinations (si différent de nœuds de population) ",
                                                              [QgsProcessing.SourceType.TypeVectorPoint],
                                                              optional = True))
                                                      
        self.addParameter(QgsProcessingParameterField(self.IDDEST, 
                                              "Colonne id pour la couche de destination",
                                              parentLayerParameterName=self.DESTINATION,
                                              optional = True))
        
        
        
        
        self.addParameter(QgsProcessingParameterFileDestination(self.MATRIX, 
                                                                "Fichier d'emplacement de la matrice de temps",
                                                                fileFilter='*.parquet',
                                                                defaultValue='*.parquet'))

    def processAlgorithm(self, parameters, context, feedback):
        pop_layer = self.parameterAsVectorLayer(parameters, self.POP, context)#QgsProcessingFeatureSource
        hubs_layer = self.parameterAsVectorLayer(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        dest_layer = self.parameterAsVectorLayer(parameters, self.DESTINATION, context)#QgsProcessingFeatureSource
        
        lignes_layer = self.parameterAsVectorLayer(parameters, self.RESEAU, context)#QgsProcessingFeatureSource
        nodes_layer = self.parameterAsVectorLayer(parameters, self.NODES, context)#QgsProcessingFeatureSource
        weight = self.parameterAsString(parameters, self.WEIGHT, context)
        id_pop = self.parameterAsString(parameters, self.IDPOP, context)
        id_hub = self.parameterAsString(parameters, self.IDHUB, context)

        id_mode = self.parameterAsInt(parameters, self.MODE, context)
        fichier_sortie=self.parameterAsFileOutput(parameters, self.MATRIX, context)

        feedback.pushInfo("Construction de la matrice de temps ...")
        modes = ['Voiture', 'Piéton', 'Vélo','Transport en commun']
        
        nodes = gdf_from_layer_arrow(nodes_layer)
        edges = gdf_from_layer_arrow(lignes_layer)
        
        print(nodes.index.dtype, edges.index.get_level_values(0).dtype)
        print(0 in nodes["osmid"].values)
        print(nodes[nodes["osmid"] == 0])
        for col in ["u", "v", "key"]:
            edges[col] = edges[col].astype("int64")
            nodes.index = nodes.index.astype("int64")
        nodes = nodes.set_index("osmid")
        nodes.index = nodes.index.astype("int64")
        edges = edges.set_index(["u", "v", "key"])
        
        if not edges.index.is_unique:
            print("Not unique !")
            edges = edges.reset_index()
            edges['key'] = edges.groupby(['u', 'v']).cumcount(ascending = True)
            edges = edges.set_index(["u", "v", "key"])
        
        print(type(edges), edges.crs, "geometry" in edges.columns)
        #print(edges.index)
        
        uv = set(edges.index.get_level_values(0)) | set(edges.index.get_level_values(1))
        missing = uv - set(nodes.index)
        print("Index manquant(s)",len(missing), list(missing)[:10])
        feedback.pushInfo(f"crs des arêtes : {edges.crs}")
        ox.convert.validate_node_edge_gdfs(nodes, edges, strict=True)
        
        G = ox.graph_from_gdfs(nodes, edges)
        

        
        print(nodes.head())
        nom = modes[id_mode]
        feedback.pushInfo(nom)

        node_field = f"node_{nom}"
        feedback.pushInfo(node_field)

        feedback.pushInfo("Recherche des nœuds les plus proches (hubs)...")
        
        feedback.pushInfo(f"crs du graphe : {G.graph['crs']}")
        nodes_hubs = add_nearest_node(hubs_layer, G, node_field, id_hub, feedback=feedback)
        if feedback.isCanceled():
            return {}
 
        feedback.pushInfo("Recherche des nœuds les plus proches (population)...")
        nodes_pop  = add_nearest_node(pop_layer, G, node_field, id_pop, feedback=feedback) #renvoie un dict
        if feedback.isCanceled():
            return {}


        all_nodes = {} #dictionnaire
        for fid, node in nodes_hubs.items():
            all_nodes[f"hub_{fid}"] = node
        for fid, node in nodes_pop.items():
            all_nodes[f"pop_{fid}"] = node
        
        #Si destination différente de pop (pour les POIs)
        if dest_layer is not None:
            id_dest = self.parameterAsString(parameters, self.IDDEST, context)
            feedback.pushInfo("Recherche des nœuds les plus proches (destinations)...")
            nodes_dest = add_nearest_node(dest_layer, G, node_field, id_dest, feedback=feedback)

            for fid, node in nodes_dest.items():
                all_nodes[f"dest_{fid}"] = node
        
        feedback.pushInfo("Fin formatage  ...")
        feedback.pushInfo(f"{len(all_nodes)} points à traiter. Calcul de la matrice de temps...")
        if feedback.isCanceled():
            return {}
        
        feedback.pushInfo(f"Écriture du fichier de sortie : {fichier_sortie}")
        matrix = build_time_matrix(G, all_nodes, weight, feedback)
        matrix = matrix.round(2)
        matrix.to_csv(fichier_sortie, index=True, float_format="%.2f")



        
        #matrix.to_csv(fichier_sortie, index=True)
        try:
            fichier_parquet = fichier_sortie
            matrix.to_parquet(fichier_parquet, index=True)
            feedback.pushInfo(f"Fichier Parquet généré pour réutilisation : {fichier_parquet}")
        except Exception as e:
            feedback.pushWarning(
                f"Export Parquet impossible ({e}) — installez pyarrow (pip install pyarrow) "
                "dans l'environnement Python de QGIS pour l'activer."
            )

        return {self.MATRIX: fichier_sortie}

        
        # dict_matrix ={}
        # index = []
        # for i in all_nodes:
        #     #Dijkstra depuis src vers tous les autres noeuds
        #     src = all_nodes[i]
        #     lengths = nx.single_source_dijkstra_path_length(
        #         G, src, weight=weight)
        #     row = {}
        #     for j in all_nodes:
        #         dest = all_nodes[j]

        #         if dest in lengths:
        #             row[str(j)] = lengths[dest]/60 #on passe des secondes aux minutes
        #         else:
        #             row[str(j)] = np.inf
        #     #feedback.pushInfo(f"ligne : {row}")
        #     dict_matrix[str(i)] = row 
        # matrix = pd.DataFrame(dict_matrix, index = index)
        
        # #renvoie un csv/txt
        # feedback.pushInfo(f"matrice : {matrix}")
        # matrix.to_csv(fichier_sortie)
        # return {self.MATRIX: fichier_sortie}
        #     #return origin,dest