# -*- coding: utf-8 -*-
"""
Created on Fri Jul 17 12:11:49 2026

@author: eleonore.lagourgue
"""

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFile,
    QgsProcessingParameterField,
    QgsFeatureSink,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant

import pandas as pd
import numpy as np
from dataclasses import dataclass, field
from collections import defaultdict


from .optimization_model import WorkplaceProblemData, WorkplaceItinerary
from mobilityhubplugin.conversions import make_wp_itinerary_fields, write_wp_itineraries_to_sink,qgis_layer_to_gdf




TRANSFER_TIME = 5   #min
MAX_TRANSFERS = 2
MODES = ["pt", "bs", "cs", "walk", "rs"]  # TC, vélo, voiture partagée

class BuildItinerariesWP(QgsProcessingAlgorithm):
    POP = "POP"
    IDPOP = "IDPOP"
    HUBS = "HUBS"
    IDHUB = "IDHUB"
    MATRIXPT = "MATRIXPT"
    MATRIXCAR ="MATRIXCAR"
    MATRIXBIKE = "MATRIXBIKE"
    MATRIXWALK = "MATRIXWALK"
    MAXRATIO = "MAXRATIO"
    MINIMPRO = "MINIMPRO"
    OUTPUT = "OUTPUT"

    def createInstance(self):
        return BuildItinerariesWP()

    def name(self):
        return "build_potential_itineraries_wp"

    def displayName(self):
        return "Construire les itinéraires potentiels (version workplace)"

    def group(self):
        return "Analyse réseau"

    def groupId(self):
        return "analyse_reseau"
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFeatureSource(self.POP, 
                                                              "Nœuds de population (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDPOP, 
                                                      "Colonne id pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(QgsProcessingParameterFeatureSource(self.HUBS,
                                                              "Hubs candidats (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDHUB, 
                                                      "Colonne id pour la couche des hubs",
                                                      parentLayerParameterName=self.HUBS))
        
        
        self.addParameter(QgsProcessingParameterFile(self.MATRIXPT, 
                                                              "Matrice de temps transportS en commun",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXCAR, 
                                                              "Matrice de temps voiture",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXBIKE, 
                                                              "Matrice de temps vélo",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXWALK, 
                                                              "Matrice de temps marche",
                                                              extension = "csv"))
        self.addParameter(QgsProcessingParameterNumber(self.MAXRATIO, 
                                                       "Ratio max avec la voiture (ex: max 3x plus lent que la voiture)", 
                                                       defaultValue=3.0))
        self.addParameter(QgsProcessingParameterNumber(self.MINIMPRO, 
                                                       "Critère de temps d'amélioration par rapport aux trasnports en commun (en %)", 
                                                       defaultValue=0.10))

        self.addParameter(QgsProcessingParameterFeatureSink(
           self.OUTPUT, "Itinéraires potentiels (table)"))
        
        
    def processAlgorithm(self, parameters, context, feedback):
        nodes_layer = self.parameterAsVectorLayer(parameters, self.POP, context)#QgsProcessingFeatureSource
        hubs_layer = self.parameterAsVectorLayer(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        matrix_pt_path = self.parameterAsFile(parameters, self.MATRIXPT, context)
        matrix_b_path = self.parameterAsFile(parameters, self.MATRIXBIKE, context)
        matrix_car_path = self.parameterAsFile(parameters, self.MATRIXCAR, context)
        matrix_w_path = self.parameterAsFile(parameters, self.MATRIXWALK, context)
        max_ratio_vs_car = self.parameterAsDouble(parameters, self.MAXRATIO, context)
        min_improvement=self.parameterAsDouble(parameters, self.MINIMPRO, context)
        
        id_nodes = self.parameterAsString(parameters, self.IDPOP,context)
        id_hubs = self.parameterAsString(parameters, self.IDHUBS,context)



        feedback.pushInfo("Construction des itinéraires potentiels (routage + élimination des dominés)...")
        matrix_pt = pd.read_csv(matrix_pt_path)
        matrix_bike = pd.read_csv(matrix_b_path)
        matrix_car = pd.read_csv(matrix_car_path)
        matrix_walk = pd.read_csv(matrix_w_path)
        
        nodes_gdf = qgis_layer_to_gdf(nodes_layer)
        hubs_gdf = qgis_layer_to_gdf(hubs_layer)
        nodes_gdf[id_nodes] = f"pop_{nodes_gdf[id_nodes]}"
        nodes_gdf = nodes_gdf.set_index(id_nodes)
        hubs_gdf[id_hubs] = f"hub_{hubs_gdf[id_hubs]}"
        hubs_gdf = hubs_gdf.set_index(id_hubs)


        itineraries = []
        iid = 0 #compteur pour créer l'id de chaque itinéraire
        
        for i, orig in nodes_gdf.items():
            for j, dest in nodes_gdf.items():
                if orig.equals( dest):
                    continue

                t_car = matrix_car.loc[i, j] #temps en voiture
                t_pt  = matrix_pt.loc[i, j] #temps de comparaison
                if t_car == np.inf or t_pt == np.inf:
                    continue
                t_max = min(t_pt, max_ratio_vs_car * t_car)
                
                # =====================================================
                #          On ajoute toujours le temps en TC
                # =====================================================
                itineraries.append(WorkplaceItinerary(
                    origin=i, destination=j,
                    mode_seq=["pt"], hubs_required=[],
                    travel_time=t_pt, id=iid
                ))
                iid += 1
                
                # =====================================================
                #          Unimodal mais que si meilleur que TC pur
                # =====================================================
                t = matrix_car[i][j] #voiture
                if t < t_pt * (1 - min_improvement) and t < t_max:
                    itineraries.append(WorkplaceItinerary(
                        origin=orig, destination=dest,
                        mode_seq=["cs"],
                        hubs_required=[(orig, "cs"), (dest, "cs")],
                        travel_time=t, itinerary_id=iid
                    ))
                    iid += 1
                    
                t = matrix_bike[i][j]#vélo
                if t < t_pt * (1 - min_improvement) and t < t_max:
                    itineraries.append(WorkplaceItinerary(
                        origin=orig, destination=dest,
                        mode_seq=["bs"],
                        hubs_required=[(orig, "bs"), (dest, "bs")],
                        travel_time=t, itinerary_id=iid
                    ))
                    iid += 1
                        
                # ========================================================
                #         Construction des itinéraires avec hubs
                # ========================================================
                
                #Pied+TC
                useful_hubs = self.get_useful_hubs(
                    i, j, hubss_gdf, 
                    matrix_pt, matrix_walk,
                    t_pt, t_max, min_improvement
                )
                for hub_id in useful_hubs:
                    walk_time = matrix_walk[hub_id][j]
                    t1 = (matrix_pt[i][hub_id] + TRANSFER_TIME
                          + walk_time)
                    if walk_time < 20 and t1 < t_pt * (1 - min_improvement) and t1 < t_max: #A chercher
                        itineraries.append(WorkplaceItinerary(
                            origin=i, destination=j,
                            mode_seq=["pt", "walk"], hubs_required=[],
                            travel_time=t1, id=iid
                        ))
                        iid += 1
                    walk_time = matrix_walk[i][hub_id]
                    t2 = (walk_time + TRANSFER_TIME
                          + matrix_pt[hub_id][j])
                    if walk_time < 20 and t2 < t_pt * (1 - min_improvement) and t2 < t_max: #A chercher
                        itineraries.append(WorkplaceItinerary(
                            origin=i, destination=j,
                            mode_seq=["walk", "pt"], hubs_required=[],
                            travel_time=t2, id=iid
                        ))
                        iid += 1
                
                #CS + TC
                useful_hubs = self.get_useful_hubs(
                        i, j, hubss_gdf, 
                        matrix_pt, matrix_car,
                        t_pt, t_max, min_improvement
                    )
                for hub_id in useful_hubs:
                    t1 = (matrix_pt[i][hub_id] + TRANSFER_TIME
                          + matrix_car[hub_id][j])
                    if t1 < t_pt * (1 - min_improvement) and t1 < t_max:
                        itineraries.append(WorkplaceItinerary(
                            origin=orig, destination=dest,
                            mode_seq=["pt", "cs"],
                            hubs_required=[(hub_id, "cs")],
                            travel_time=t1, time_car = t_car, itinerary_id=iid
                        ))
                        iid += 1
                    # Mode à demande jusqu'au hub, puis TC
                    t2 = (matrix_car[i][hub_id] + TRANSFER_TIME
                          + matrix_pt[hub_id][j])
                    if t2 < t_pt * (1 - min_improvement) and t2 < t_max:
                        itineraries.append(WorkplaceItinerary(
                            origin=orig, destination=dest,
                            mode_seq=["cs", "pt"],
                            hubs_required=[(hub_id, "cs")],
                            travel_time=t2,  time_car = t_car,itinerary_id=iid
                        ))
                        iid += 1
                #BS + TC
                useful_hubs = self.get_useful_hubs(
                        i, j, hubss_gdf, 
                        matrix_pt, matrix_bike,
                        t_pt, t_max, min_improvement
                    )
                for hub_id in useful_hubs:
                    t1 = (matrix_pt[i][hub_id] + TRANSFER_TIME
                          + matrix_bike[hub_id][j])
                    if t1 < t_pt * (1 - min_improvement) and t1 < t_max:
                        itineraries.append(WorkplaceItinerary(
                            origin=orig, destination=dest,
                            mode_seq=["pt", "cs"],
                            hubs_required=[(hub_id, "cs")],
                            travel_time=t1, time_car = t_car, itinerary_id=iid
                        ))
                        iid += 1
                    # Mode à demande jusqu'au hub, puis TC
                    t2 = (matrix_bike[i][hub_id] + TRANSFER_TIME
                          + matrix_pt[hub_id][j])
                    if t2 < t_pt * (1 - min_improvement) and t2 < t_max:
                        itineraries.append(WorkplaceItinerary(
                            origin=orig, destination=dest,
                            mode_seq=["cs", "pt"],
                            hubs_required=[(hub_id, "cs")],
                            travel_time=t2,  time_car = t_car,itinerary_id=iid
                        ))
                        iid += 1
                        
        iti_finaux =self.elimination_itineraires_domines(itineraries)
        #nodes_src, hubs_src, pois_src, threshold, budget, feedback
       
        feedback.pushInfo(f"{len(iti_finaux)} itinéraires potentiels générés. Résolution du MIP...")
        
        #Ecriture du résultat
        fields = make_wp_itinerary_fields()
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT_ITINERARIES, context, fields,
            QgsWkbTypes.NoGeometry)  #pas de géométrie : c'est une table pure

        write_wp_itineraries_to_sink(iti_finaux, sink)
        return {self.OUTPUT: dest_id}
    
        
    def get_useful_hubs(i, j, hubs_potentiels, 
                        mat_pt, mat_car, t_pt, t_max, min_improvement):
        """
        Ne retourne que les hubs h tels que :
        - PT(i vers h) + CAR(h vers j) < t_pt * (1 - min_improvement)
        - ou CAR(i vers h) + PT(h vers j) < t_pt * (1 - min_improvement)
        Évite d'énumérer tous les hubs pour chaque paire O-D.
        """
        useful = []
        for hub_id in hubs_potentiels:
            print(hub_id)
             
            t1 = mat_pt[i][hub_id] + TRANSFER_TIME + mat_car[hub_id][j]
            t2 = mat_car[i][hub_id] + TRANSFER_TIME + mat_pt[hub_id][j]
            
            if (t1 < t_pt * (1 - min_improvement) and t1 < t_max) or \
               (t2 < t_pt * (1 - min_improvement) and t2 < t_max) :
                useful.append(hub_id)
        return useful
    def elimination_itineraires_domines(itineraires):
        by_od = defaultdict(list)
        for it in itineraires:
            by_od[(it.origin, it.destination)].append(it)
            #Construit dictionnaire avec comme clé origine& destination

        kept = []
        for od, itis in by_od.items():
            its_sorted = itis.sort_values(by = ["travel_time"])
            non_dominated = []
            for cand in its_sorted:
                dominated = False
                req_c = set(cand.hubs_required)
                for better in non_dominated:
                    req_b = set(better.hubs_required)
                    # cand dominé si ses requirements sont un surensemble de ceux de better
                    # ET better est plus rapide (garanti par le tri i.e. sorted)
                    if req_b.issubset(req_c):
                        dominated = True
                        break
                if not dominated:
                    non_dominated.append(cand)
            kept.extend(non_dominated)

        return kept





