# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import datetime
import partridge as ptg
import geopandas as gpd
import pandas as pd
import osmnx as ox
import networkx as nx
import pickle
from shapely.geometry import Point,MultiPoint, LineString
from shapely.ops import substring
import zipfile
import os
import io
import gc

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)
from qgis.core import *

from mobilityhubplugin.conversions import gdf_from_layer_arrow

class CreaShapesAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    
    REP_GTFS = "REP_GTFS"
    NODES_TRAIN = "NODES_TRAIN"
    RESEAU_TRAIN = "RESEAU_TRAIN"
    WEIGHT_TRAIN = "WEIGHT_TRAIN"
    
    NODES_VOITURE = "NODES_VOITURE"
    RESEAU_VOITURE = "RESEAU_VOITURE"
    WEIGHT_VOITURE = "WEIGHT_VOITURE"
  
    OUTPUT = 'OUTPUT'
    
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Créer un fichier shapes.txt pour les GTFS'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return 'Traitements annexes'

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'traitements_annexes'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile( 
                self.REP_GTFS,
                self.tr('zip GTFS'),
                QgsProcessingParameterFile.File,
                extension='zip',
                optional=False
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.TRAIN, "Chemin de fer (pour les trains)"))
        self.addParameter(QgsProcessingParameterFeatureSource(self.NODES_TRAIN, 
                                                              "Nœuds du réseau ferré (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterFeatureSource(self.RESEAU_TRAIN, 
                                                              "Lignes du réseau ferré (lignes)",
                                                              [QgsProcessing.SourceType.TypeVectorLine]))
        
        self.addParameter(QgsProcessingParameterField(self.WEIGHT_TRAIN, 
                                              "Colonne poids réseau ferré",
                                              parentLayerParameterName=self.RESEAU_TRAIN))
        
        self.addParameter(QgsProcessingParameterFeatureSource(self.NODES_VOITURE, 
                                                              "Nœuds du réseau routier (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterFeatureSource(self.RESEAU_VOITURE, 
                                                              "Lignes du réseau routier (lignes)",
                                                              [QgsProcessing.SourceType.TypeVectorLine]))
        
        self.addParameter(QgsProcessingParameterField(self.WEIGHT_VOITURE, 
                                              "Colonne poids réseau routier",
                                              parentLayerParameterName=self.RESEAU_VOITURE))
        

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        
        zip_gtfs = self.parameterAsFile(parameters, self.REP_GTFS, context)
        
        lignes_layer = self.parameterAsVectorLayer(parameters, self.RESEAU_TRAIN, context)#QgsProcessingFeatureSource
        nodes_layer = self.parameterAsVectorLayer(parameters, self.NODES_TRAIN, context)#QgsProcessingFeatureSource
        weight_train = self.parameterAsString(parameters, self.WEIGHT_TRAIN, context)
        
        
        nodes_train = gdf_from_layer_arrow(nodes_layer)
        edges_train = gdf_from_layer_arrow(lignes_layer)
        nodes_train = nodes_train.set_index("osmid")
        edges_train = edges_train.set_index(["u", "v", "key"])
        G_train = ox.graph_from_gdfs(nodes_train, edges_train)
        
        
        lignes_layer = self.parameterAsVectorLayer(parameters, self.RESEAU_VOITURE, context)#QgsProcessingFeatureSource
        nodes_layer = self.parameterAsVectorLayer(parameters, self.NODES_VOITURE, context)#QgsProcessingFeatureSource
        weight_voiture = self.parameterAsString(parameters, self.WEIGHT_VOITURE, context)
        
        
        nodes_voiture = gdf_from_layer_arrow(nodes_layer)
        edges_voiture = gdf_from_layer_arrow(lignes_layer)
        nodes_voiture = nodes_voiture.set_index("osmid")
        edges_voiture = edges_voiture.set_index(["u", "v", "key"])
        G_voiture = ox.graph_from_gdfs(nodes_voiture, edges_voiture)


        feed = ptg.load_feed(zip_gtfs)
        stop_times = feed.stop_times
        trips = feed.trips    
        stops = feed.stops
        routes = feed.routes
        
        
        feedback.pushInfo("Création de l'id shape")

        seq_id = stop_times.sort_values(['trip_id','stop_sequence']).groupby('trip_id')['stop_id'].apply(tuple)
        seq_name = (stop_times.merge(stops[['stop_id','stop_name']], on='stop_id')
                    .sort_values(['trip_id','stop_sequence'])
                    .groupby('trip_id')['stop_name'].apply(tuple))

        check = pd.DataFrame({'seq_id': seq_id, 'seq_name': seq_name})
        check = check.merge(trips[['trip_id','route_id']], left_index=True, right_on='trip_id')

        # Pour un même (route_id, seq_name), combien de seq_id distincts ?
        pb = check.groupby(['route_id','seq_name'])['seq_id'].nunique()
        print(pb[pb > 1])

        #Construction shape_id
        sequences = (
            stop_times.sort_values(['trip_id', 'stop_sequence'])
            .groupby('trip_id')['stop_id']
            .apply(tuple)  # tuple = hashable, comparable
        )
        trips = trips.merge(
            sequences.rename('stop_sequence_tuple'),
            left_on='trip_id', right_index=True
        )

        trips['shape_id'] = trips.groupby(
            ['route_id', 'direction_id', 'stop_sequence_tuple']
        ).ngroup()

        check = trips.groupby('shape_id')['stop_sequence_tuple'].nunique()
        print("Max de séquences différentes par shape_id (doit être 1) :", check.max())
        trips = trips.drop(columns=['stop_sequence_tuple'])


        stops_avec_temps = stops.merge(stop_times, on="stop_id", how ="right")
        iti = stops_avec_temps.merge(trips, on = "trip_id")
        iti = iti.merge(routes[['route_id', 'route_type', 'route_long_name']], on = "route_id")

        # iti["shape_id"] = iti["route_id"]+"_"+ iti["trip_headsign"] #test
        # trips["shape_id"]= trips["route_id"]+"_"+ trips["trip_headsign"]

        shapes = gpd.GeoDataFrame(
        iti, 
        geometry=gpd.points_from_xy(iti.stop_lon, iti.stop_lat), 
        crs="EPSG:4326")
        shapes = shapes.to_crs(2154)

        #Enlever les doublons
        shapes = shapes.drop_duplicates(subset = ['shape_id', "stop_id", "geometry", "route_id"])
        doublons = shapes.duplicated(subset=['shape_id', 'stop_sequence'], keep=False)
        
        if doublons.any():
            nb_shapes_touches = shapes.loc[doublons, 'shape_id'].nunique()
            msg = f"{doublons.sum()} doublons sur (shape_id, stop_sequence), {nb_shapes_touches} shape_id touchés."
            feedback.pushWarning(msg)

           
        else:
        
            feedback.pushInfo("OK : (shape_id, stop_sequence) est unique, pas de coordonnées ambiguës.")
        # ----------- Préparation des GeoDataFrames d'arêtes ---------------------
        
        all_shapes = []
        groupes = list(shapes_gdf.groupby("shape_id"))
        nb_groupes = len(groupes)
        for i_grp, (shape_id, group) in enumerate(groupes):
            if feedback.isCanceled():
                feedback.pushWarning("Traitement annulé par l'utilisateur.")
                break
     
            feedback.setProgress(100 * i_grp / max(nb_groupes, 1))

        

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, train.fields(), train.wkbType(), train.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / train.featureCount() if train.featureCount() else 0
        features = train.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {}

    def ajuster_segment(geom, point_ref, debut=True):
        if geom.geom_type != 'LineString':
            # Pas une ligne exploitable : on ne peut pas découper, on garde tel quel
            # ou on la remplace par une ligne droite minimale si besoin
            return geom
        dist = geom.project(point_ref)
        if debut:
            return substring(geom, dist, geom.length)
        else:
            return substring(geom, 0, dist)
    def findnearestnodeonnearestedge(Gr, X, Y):
        """
        source : https://stackoverflow.com/questions/68257014/how-to-find-nearest-node-along-nearest-edge

        Parameters
        ----------
        Gr : graphe au format osmnx
        X : TYPE
            DESCRIPTION.
        Y : TYPE
            DESCRIPTION.

        Returns
        -------
        nodeid : TYPE
            DESCRIPTION.

        """

        edge,dist = ox.distance.nearest_edges(Gr, X,Y, return_dist=True)
        u, v, key = edge
        edge_data = Gr.edges[u, v, key]
        edge_geom = edge_data["geometry"]

        n1 = Gr.nodes[u]
        n2 = Gr.nodes[v]

        d1 = ox.distance.euclidean(Y,X, n1['y'], n1['x'])
        d2 = ox.distance.euclidean(Y,X, n2['y'], n2['x'])
        
        point = Point(X, Y)
        dist_along = edge_geom.project(point)

        if d1 < d2:
            nodeid = u
            autre_node= v
        else:
            nodeid = v
            autre_node= u
        
        node_point = Point(Gr.nodes[nodeid]['x'], Gr.nodes[nodeid]['y'])
        dist_node_on_edge = edge_geom.project(node_point)


        

        return nodeid, dist, edge_geom, dist_along, dist_node_on_edge




    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CreaShapesAlgorithm()
