# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



# build_graph_algorithm.py
from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingParameterVectorLayer,
    QgsVectorLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterEnum,
    QgsProcessingParameterField,
    QgsProcessingOutputString,
    QgsProcessingOutputLayerDefinition,
    QgsProcessingParameterString,
    QgsProcessingParameterFeatureSink,
    QgsFeature, QgsGeometry, QgsFields, QgsField,
    QgsWkbTypes, QgsCoordinateReferenceSystem,
)
from qgis.analysis import QgsVectorLayerDirector
from qgis.PyQt.QtCore import QVariant, QCoreApplication

from .conversions import (qgis_layer_to_gdf, 
                         gdf_geom_to_qgs_wkbtype,
                         gdf_to_qgsfields,
                         write_gdf_to_sink)

#Bibliothèques python
import osmnx as ox
import numpy as np
import pandas as pd
import networkx as nx
import geopandas as gpd
import partridge as ptg
from shapely import ops as sops
from scipy.spatial import cKDTree
from shapely import distance

class BuildGraphGTFSAlgorithm(QgsProcessingAlgorithm):

    INPUT = "INPUT"
    LIGNES = 'LIGNES'
    NOEUDS = "NOEUDS"
    def __init__(self):
        super().__init__()
    def name(self): return "build_graph_gtfs"
    def displayName(self): return "Construire le graphe réseau à partir d'un zip gtfs"
    def createInstance(self): return BuildGraphGTFSAlgorithm()
    def group(self): return "Réseau"
    def groupId(self): return "reseau"
    def tr(self, string):
        return QCoreApplication.translate('BuildGraphGTFSAlgorithm', string)
    def initAlgorithm(self, config=None):
        
        
        self.addParameter(QgsProcessingParameterVectorLayer(self.INPUT, self.tr("Réseau")))
        self.addParameter(QgsProcessingParameterFeatureSink(self.LIGNES, self.tr("Couche linéaire du graphe")))
        self.addParameter(QgsProcessingParameterFeatureSink(self.NOEUDS, self.tr("Couche des noeuds du graphe")))
    
    
    
    def processAlgorithm(self, parameters, context, feedback):
        zip_path = self.parameterasFile(parameters, self.INPUT, context)
        
        
        #Load gtfs with partridge
        feed = ptg.load_geo_feed(zip_path, view={})