# -*- coding: utf-8 -*-
"""
Created on Tue Jul 21 11:25:08 2026

@author: eleonore.lagourgue
"""
"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFile,
    QgsProcessingParameterField,
    QgsFeatureSink,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant

import pandas as pd
import numpy as np
from dataclasses import dataclass, field
from collections import defaultdict

from .optimization_model import  Itinerary,ProblemData
from mobilityhubplugin.conversions import make_poi_itinerary_fields, write_poi_itineraries_to_sink
from mobilityhubplugin.conversions import gdf_from_layer_arrow

TRANSFER_TIME = 5   #min
MAX_TRANSFERS = 2
MODES = ["pt", "bs", "cs", "walk", "rs"]  # TC, vélo, voiture partagée

def build_parking_demand(hubs_required, d_s, usage_rate):
    return {(l, m): d_s * usage_rate[m] for (l, m) in hubs_required}
def get_useful_hubs(i, j, hubs_potentiels, 
                    mat_pt, mat_car, t_pt, t_max, min_improvement):
    """
    Ne retourne que les hubs h tels que :
    - PT(i vers h) + CAR(h vers j) < t_pt * (1 - min_improvement)
    - ou CAR(i vers h) + PT(h vers j) < t_pt * (1 - min_improvement)
    Évite d'énumérer tous les hubs pour chaque paire O-D.
    """
    useful = []
    for hub_id in hubs_potentiels.index:
        print(hub_id)
         
        t1 = mat_pt.loc[i,hub_id] + TRANSFER_TIME + mat_car.loc[hub_id,j]
        t2 = mat_car.loc[i,hub_id] + TRANSFER_TIME + mat_pt.loc[hub_id,j]
        
        if (t1 < t_pt * (1 - min_improvement) and t1 < t_max) or \
           (t2 < t_pt * (1 - min_improvement) and t2 < t_max) :
            useful.append(hub_id)
    return useful
def elimination_itineraires_domines(itineraires):
    by_od = defaultdict(list)
    for it in itineraires:
        by_od[(it.node, it.poi_category)].append(it)
        #Construit dictionnaire avec comme clé noeud d'origine et la catégorie de poi

    kept = []
    for od, itis in by_od.items():
        its_sorted = sorted(itis, key=lambda it: it.travel_time)
        non_dominated = []
        for cand in its_sorted:
            dominated = False
            req_c = set(cand.hubs_required)
            for better in non_dominated:
                req_b = set(better.hubs_required)
                # cand dominé si ses requirements sont un surensemble de ceux de better
                # ET better est plus rapide (garanti par le tri i.e. sorted)
                if req_b.issubset(req_c):
                    dominated = True
                    break
            if not dominated:
                non_dominated.append(cand)
        kept.extend(non_dominated)

    return kept

class BuildItinerariesPOI(QgsProcessingAlgorithm):
    POP = "POP"
    IDPOP = "IDPOP"
    COLPOP = "COLPOP"
    HUBS = "HUBS"
    IDHUB = "IDHUB"
    DESTINATION = "DESTINATION"
    IDDEST ="IDDEST"
    MATRIXPT = "MATRIXPT"
    MATRIXCAR ="MATRIXCAR"
    MATRIXBIKE = "MATRIXBIKE"
    MATRIXWALK = "MATRIXWALK"
    BUDGET = "BUDGET"
    MAXRATIO = "MAXRATIO"
    MINIMPRO = "MINIMPRO"
    OUTPUT = "OUTPUT"

    def createInstance(self):
        return BuildItinerariesPOI()

    def name(self):
        return "build_potential_itineraries_poi"

    def displayName(self):
        return "Construire les itinéraires potentiels (version POI)"

    def group(self):
        return "Analyse réseau"

    def groupId(self):
        return "analyse_reseau"
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFeatureSource(self.POP, 
                                                              "Nœuds de population (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDPOP, 
                                                      "Colonne id pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(QgsProcessingParameterField(self.COLPOP, 
                                                      "Colonne population pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(QgsProcessingParameterFeatureSource(self.HUBS,
                                                              "Hubs candidats (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterField(self.IDHUB, 
                                                      "Colonne id pour la couche des hubs",
                                                      parentLayerParameterName=self.HUBS))
        
        self.addParameter(QgsProcessingParameterFeatureSource(self.DESTINATION,
                                                              "Destinations (si différent de nœuds de population) ",
                                                              [QgsProcessing.SourceType.TypeVectorPoint],
                                                              optional = True))
                                                      
        self.addParameter(QgsProcessingParameterField(self.IDDEST, 
                                              "Colonne id pour la couche de destination",
                                              parentLayerParameterName=self.DESTINATION,
                                              ))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXPT, 
                                                              "Matrice de temps transportS en commun",
                                                              extension = "parquet"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXCAR, 
                                                              "Matrice de temps voiture",
                                                              extension = "parquet"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXBIKE, 
                                                              "Matrice de temps vélo",
                                                              extension = "parquet"))
        self.addParameter(QgsProcessingParameterFile(self.MATRIXWALK, 
                                                              "Matrice de temps marche",
                                                              extension = "parquet"))
        self.addParameter(QgsProcessingParameterNumber(self.MAXRATIO, 
                                                       "Ratio max avec la voiture (ex: max 3x plus lent que la voiture)", 
                                                       defaultValue=3.0))
        self.addParameter(QgsProcessingParameterNumber(self.MINIMPRO, 
                                                       "Critère de temps d'amélioration par rapport aux trasnports en commun (en %)", 
                                                       defaultValue=0.10))

        self.addParameter(QgsProcessingParameterFeatureSink(
           self.OUTPUT, "Itinéraires potentiels (table)"))

    def processAlgorithm(self, parameters, context, feedback):
        nodes_layer = self.parameterAsVectorLayer(parameters, self.POP, context)#QgsProcessingFeatureSource
        hubs_layer = self.parameterAsVectorLayer(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        dest_layer = self.parameterAsVectorLayer(parameters, self.DESTINATION, context)#QgsProcessingFeatureSource
        matrix_pt_path = self.parameterAsFile(parameters, self.MATRIXPT, context)
        matrix_b_path = self.parameterAsFile(parameters, self.MATRIXBIKE, context)
        matrix_car_path = self.parameterAsFile(parameters, self.MATRIXCAR, context)
        matrix_w_path = self.parameterAsFile(parameters, self.MATRIXWALK, context)
        max_ratio_vs_car = self.parameterAsDouble(parameters, self.MAXRATIO, context)
        min_improvement=self.parameterAsDouble(parameters, self.MINIMPRO, context)
        
        id_nodes = self.parameterAsString(parameters, self.IDPOP,context)
        print(id_nodes)
        id_hubs = self.parameterAsString(parameters, self.IDHUB,context)
        pop_column = self.parameterAsString(parameters, self.COLPOP,context)
        id_dest = self.parameterAsString(parameters, self.IDDEST,context)


        feedback.pushInfo("Construction des itinéraires potentiels (routage + élimination des dominés)...")
        #Import
        matrix_pt = pd.read_parquet(matrix_pt_path,)
        matrix_bike = pd.read_parquet(matrix_b_path)
        matrix_car = pd.read_parquet(matrix_car_path)
        matrix_walk = pd.read_parquet(matrix_w_path)
        
      
        #feedback.pushInfo(f"{matrix_car.columns} : colonnes matrice voiture")
        feedback.pushInfo(f"{len(matrix_walk)} : taille matrice marche")


        #Formatage
        nodes_gdf = gdf_from_layer_arrow(nodes_layer)
        hubs_gdf = gdf_from_layer_arrow(hubs_layer)
        dest_gdf = gdf_from_layer_arrow(dest_layer)
        
        #feedback.pushInfo(f"{nodes_gdf[id_nodes][:5]} : index pop avant modif")
        #print(nodes_gdf[id_nodes][:5])

        nodes_gdf[id_nodes] = "pop_" + nodes_gdf[id_nodes].astype(str)
        nodes_gdf = nodes_gdf.set_index(id_nodes)
        #feedback.pushInfo(f"{nodes_gdf.index} : index pop")

        
        dest_gdf[id_dest] = "dest_" + dest_gdf[id_dest].astype(str)
        dest_gdf = dest_gdf.set_index(id_dest)
        #dest_gdf = dest_gdf["category_id"]
        
        hubs_gdf[id_hubs] = "hub_" + hubs_gdf[id_hubs].astype(str)
        hubs_gdf = hubs_gdf.set_index(id_hubs)
        
        usage_rate = {"bs": 0.001, "cs": 0.001, "pt": 1.0}

        itineraries = []
        iid = 0 #compteur pour créer l'id de chaque itinéraire
        pop = nodes_gdf[pop_column]
        for row_a in nodes_gdf.itertuples():
            i = row_a[0]
            #feedback.pushInfo(f"ID origine :{i}")
            d_s = pop.loc[str(i)] if (str(i) in pop.index ) else 0.0
            #feedback.pushInfo(f"d_s : {d_s}")

            for row_b in dest_gdf.itertuples():
                j = row_b[0]
                cate = row_b[1]
                #feedback.pushInfo(f"ID destination :{j}")

                if i== j:
                    feedback.pushInfo(f"Mêmes rows : {row_a}, \n{row_b}")
                    #Normalement impossible
                    continue

                t_car = matrix_car.loc[i, j] #temps en voiture
                t_pt  = matrix_pt.loc[i, j] #temps de comparaison
                if t_car == np.inf or t_pt == np.inf:
                    continue
                t_max = min(t_pt, max_ratio_vs_car * t_car)
                
                # =====================================================
                #          On ajoute toujours le temps en TC
                # =====================================================
                itineraries.append(Itinerary(
                    node=i,
                     hubs_required=[],
                    travel_time=t_pt, id=iid, parking_demand = {},
                    poi_category = cate,
                ))
                iid += 1
                #feedback.pushInfo(f"Ratio voiture / TC : {t_car/t_pt}")

                # =====================================================
                #          Unimodal mais que si meilleur que TC pur
                # =====================================================
                t = matrix_car[i][j] #voiture
                if t < t_pt * (1 - min_improvement) and t < t_max:
                    hubs_req = [(i, "cs"), (j, "cs")]

                    itineraries.append(Itinerary(
                        node=i,
                        hubs_required=hubs_req,
                        travel_time=t, id=iid,
                        parking_demand=build_parking_demand(hubs_req, d_s, usage_rate),
                        poi_category = cate,
                    ))
                    iid += 1
                    
                t = matrix_bike[i][j]#vélo
                if t < t_pt * (1 - min_improvement) and t < t_max:
                    hubs_req = [(i, "bs"), (j, "bs")]

                    itineraries.append(Itinerary(
                        node=i,
                        hubs_required=hubs_req,
                        travel_time=t, id=iid,
                        parking_demand=build_parking_demand(hubs_req, d_s, usage_rate),
                        poi_category = cate,
                    ))
                    iid += 1
                        
                # ========================================================
                #         Construction des itinéraires avec hubs
                # ========================================================
                
                
                #feedback.pushInfo("Recherche avc des hubs")
                #CS + TC
                useful_hubs = get_useful_hubs(
                        i, j, hubs_gdf, 
                        matrix_pt, matrix_car,
                        t_pt, t_max, min_improvement
                    )
                for hub_id in useful_hubs:
                    t1 = (matrix_pt[i][hub_id] + TRANSFER_TIME
                          + matrix_car[hub_id][j])
                    if t1 < t_pt * (1 - min_improvement) and t1 < t_max:
                        hubs_req = [(hub_id, "cs"), (j, "cs")]

                        itineraries.append(Itinerary(
                            node=i,
                            hubs_required=hubs_req,
                            travel_time=t1,  id=iid,
                            parking_demand=build_parking_demand(hubs_req, d_s, usage_rate),
                            poi_category = cate,
                        ))
                        iid += 1
                    # Mode à demande jusqu'au hub, puis TC
                    t2 = (matrix_car[i][hub_id] + TRANSFER_TIME
                          + matrix_pt[hub_id][j])
                    if t2 < t_pt * (1 - min_improvement) and t2 < t_max:
                        hubs_req = [(hub_id, "cs"), (i, "cs")]
                        itineraries.append(Itinerary(
                            node=i,
                            hubs_required=hubs_req,
                            travel_time=t2,  id=iid,
                            parking_demand=build_parking_demand(hubs_req, d_s, usage_rate),
                            poi_category = cate,
                        ))
                        iid += 1
                
                #BS + TC
                useful_hubs = get_useful_hubs(
                        i, j, hubs_gdf, 
                        matrix_pt, matrix_bike,
                        t_pt, t_max, min_improvement
                    )
                for hub_id in useful_hubs:
                    t1 = (matrix_pt[i][hub_id] + TRANSFER_TIME
                          + matrix_bike[hub_id][j])
                    if t1 < t_pt * (1 - min_improvement) and t1 < t_max:
                        hubs_req = [(hub_id, "bs"), (j, "bs")]

                        itineraries.append(Itinerary(
                            node=i,
                            hubs_required=hubs_req,
                            travel_time=t1,  id=iid,
                            parking_demand=build_parking_demand(hubs_req, d_s, usage_rate),
                            poi_category = cate,
                        ))
                        iid += 1
                    # Mode à demande jusqu'au hub, puis TC
                    t2 = (matrix_bike[i][hub_id] + TRANSFER_TIME
                          + matrix_pt[hub_id][j])
                    if t2 < t_pt * (1 - min_improvement) and t2 < t_max:
                        hubs_req = [(hub_id, "bs"), (i, "bs")]

                        itineraries.append(Itinerary(
                            node=i,
                            hubs_required=hubs_req,
                            travel_time=t2,  id=iid,
                            parking_demand=build_parking_demand(hubs_req, d_s, usage_rate),
                            poi_category = cate,
                        ))
                        iid += 1
        feedback.pushInfo("Fin de la recherche")            
        iti_finaux = elimination_itineraires_domines(itineraries)
        #nodes_src, hubs_src, pois_src, threshold, budget, feedback
       
        feedback.pushInfo(f"{len(iti_finaux)} itinéraires potentiels générés. Résolution du MIP...")
        
        
        #Ecriture du résultat
        fields = make_poi_itinerary_fields()
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context, fields,
            QgsWkbTypes.NoGeometry)  #pas de géométrie : c'est une table pure
        list_dict =[]
        for it in iti_finaux:
            list_dict.append({"id":it.id, "node": it.node,
                              "poi_category": it.poi_category, 
                              "travel_time": it.travel_time,
                              "parking_demand": it.parking_demand, 
                              "hubs_required": it.hubs_required,
                              })

        write_poi_itineraries_to_sink(iti_finaux, sink)
        return {self.OUTPUT: dest_id}
    
    
    
