# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

#Python
import datetime
import partridge as ptg
import geopandas as gpd
import pandas as pd
import os
from shapely import wkt
import gc
import zipfile

#QGIS
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsCoordinateReferenceSystem,
                       QgsCoordinateTransform,
                       QgsProject,
                       QgsPointXY,
    )
from qgis.core import *
import processing

#Plugin
from mobilityhubplugin.conversions import gdf_from_layer_arrow



class DecoupeGTFSAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    
    REP_GTFS = "REP_GTFS"
    EMPRISE ="EMPRISE"
  
    OUTPUT_PATH = 'OUTPUT_PATH'
    
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Découper un GTFS selon une emprise'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return 'Formatage préliminaire'

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'formatage'
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DecoupeGTFSAlgorithm()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile( 
                self.REP_GTFS,
                self.tr('zip GTFS'),
                QgsProcessingParameterFile.File,
                extension='zip',
                optional=False
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource( 
                self.EMPRISE,
                self.tr("Couche d'emprise de la zone d'intérêt"),
                optional=False
            )
        )
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_PATH,
                self.tr('Chemin de sortie'),
                fileFilter = "*.zip",
                defaultValue='*.zip',
                optional=False

                
            )
        )
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        
        zip_gtfs = self.parameterAsFile(parameters, self.REP_GTFS, context)
        #emprise = self.parameterasSource(parameters, self.EMPRISE, context)
        sortie=(self.parameterAsFileOutput(parameters, self.OUTPUT_PATH, context))

        feedback.pushInfo(zip_gtfs)
        feedback.pushInfo(f"Chemin de sortie : {sortie}")
        #Reprojection
        # crsSrc = emprise.sourceCrs()
        # crsSrc = QgsCoordinateReferenceSystem("EPSG:2154")        
        crsDest = QgsCoordinateReferenceSystem("EPSG:4326")
        # transformContext = context.transformContext()        
        # xform = QgsCoordinateTransform(crsSrc, crsDest, transformContext)
        # emprise_reproj = xform.transform(emprise)
        
        reprojected  = processing.run("native:reprojectlayer", {
            'INPUT':parameters["EMPRISE"],
            'TARGET_CRS':crsDest,
            'CONVERT_CURVED_GEOMETRIES':False,
            'OUTPUT':'memory:'}, 
            context=context, feedback=feedback)['OUTPUT']
        
        feed = ptg.load_feed(zip_gtfs)
        
        # Liste des tables standards GTFS à extraire si elles existent
        tables = ['stops','agency',  'routes', 'trips', 'stop_times', 'calendar', 'calendar_dates', 'transfers',"shapes"]
        feed_dfs = {}
        
        for table in tables:
            try:
                df = getattr(feed, table).copy()
                if df.empty:
                    feedback.pushWarning(f"La table {table} est vide")

                    #continue
                feed_dfs[table] = df
                
            except AttributeError:
                # La table n'existe pas dans ce flux, on passe
                feedback.pushInfo(f"Pas de fichier {table} dans le zip")
                continue
        
        polygon = processing.run("native:coverageunion", {'INPUT': reprojected
                                                          ,'OUTPUT':'memory:'},
                                 context=context, feedback=feedback)['OUTPUT']
        polygon_feat = next(polygon.getFeatures())
        polygon_geom = wkt.loads(polygon_feat.geometry().asWkt())
        
        #On sélectiones les arrêts dans le périmètre
        stops = feed_dfs["stops"]
        stops_gdf = gpd.GeoDataFrame(
        stops,
            geometry=gpd.points_from_xy(stops['stop_lon'], stops['stop_lat']),
            crs='EPSG:4326'
        )
        
        filtered_stops_gdf = stops_gdf[stops_gdf.geometry.within(polygon_geom)]
        valid_stop_ids = set(filtered_stops_gdf['stop_id'])
      
        stop_times = feed_dfs["stop_times"]
        filtered_stop_times = stop_times[stop_times['stop_id'].isin(valid_stop_ids)]
        valid_trip_ids = set(filtered_stop_times['trip_id'])
        
        # Optionnel mais recommandé : On conserve l'INTÉGRALITÉ des arrêts pour les trips sélectionnés
        # pour éviter de casser la continuité d'une ligne. Si vous voulez un découpage strict à la frontière,
        # décommentez la ligne suivante :
        # feed_dfs['stop_times'] = filtered_stop_times
        feed_dfs['stop_times'] = stop_times[stop_times['trip_id'].isin(valid_trip_ids)]
        print(f"Horaires (stop_times) conservés : {stop_times}")
        
        
        trips_df = feed_dfs['trips']
        feed_dfs['trips'] = trips_df[trips_df['trip_id'].isin(valid_trip_ids)]
        valid_route_ids = set(feed_dfs['trips']['route_id'])
        valid_service_ids = set(feed_dfs['trips']['service_id'])
        valid_shape_ids = set(feed_dfs['trips']['shape_id'].dropna())

        # --- ÉTAPE 4 : Filtrer les ROUTES ---
        routes_df = feed_dfs['routes']
        feed_dfs['routes'] = routes_df[routes_df['route_id'].isin(valid_route_ids)]
        valid_agency_ids = set(feed_dfs['routes']['agency_id'].dropna())

        # --- ÉTAPE 5 : Filtrer les calendriers (CALENDAR & CALENDAR_DATES) ---
        if 'calendar' in feed_dfs:
            feed_dfs['calendar'] = feed_dfs['calendar'][feed_dfs['calendar']['service_id'].isin(valid_service_ids)]
        if 'calendar_dates' in feed_dfs:
            feed_dfs['calendar_dates'] = feed_dfs['calendar_dates'][feed_dfs['calendar_dates']['service_id'].isin(valid_service_ids)]

        # --- ÉTAPE 6 : Filtrer les tracés géométriques (SHAPES) ---
        if 'shapest' in feed_dfs:
            feed_dfs['shapes'] = feed_dfs['shapes'][feed_dfs['shapes']['shape_id'].isin(valid_shape_ids)]

        # --- ÉTAPE 7 : Filtrer les agences (AGENCY) ---
        if 'agency' in feed_dfs and len(valid_agency_ids) > 0:
            feed_dfs['agency'] = feed_dfs['agency'][feed_dfs['agency']['agency_id'].isin(valid_agency_ids)]

        # Si on a gardé l'intégralité des arrêts pour les trajets valides (option recommandée),
        # il faut ré-enrichir la table stops pour inclure les arrêts hors-zone où ces trajets s'arrêtent.
        all_needed_stops = set(feed_dfs['stop_times']['stop_id'])
        feed_dfs['stops'] = stops[stops['stop_id'].isin(all_needed_stops)]
        
        with zipfile.ZipFile(sortie, 'w', zipfile.ZIP_DEFLATED) as out_z:
            for file_name, df in feed_dfs.items():
                if not df.empty:
                    out_z.writestr(f"{file_name}.txt", df.to_csv(index=False))
                    print(f"{file_name} écrit.")
        gc.collect()

        return {'SORTIE': sortie}




