# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .algo_shapes import CreaShapesAlgorithm
from .algo_poi import LocateHubsPOIAlgorithm
from .algo_workplace import LocateHubsWorkplaceAlgorithm
from .algo_graph  import BuildGraphAlgorithm
from .algo_matricetemps  import MatriceTemps
from .algo_itineraires_wp  import BuildItinerariesWP
from .algo_itineraires_poi import BuildItinerariesPOI
from .algo_pente import AddGradeAlgorithm
from.algo_od import FormateODmatrix
from .algo_decoup_gtfs import DecoupeGTFSAlgorithm
from .algo_graph_gtfs import BuildGraphGTFSAlgorithm
from .algo_merge_gtfs import MergeGTFS


class MobilityHubPluginProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(CreaShapesAlgorithm())
        self.addAlgorithm(LocateHubsPOIAlgorithm())
        self.addAlgorithm(LocateHubsWorkplaceAlgorithm())
        self.addAlgorithm(BuildGraphAlgorithm())
        self.addAlgorithm(MatriceTemps())
        self.addAlgorithm(BuildItinerariesWP())
        self.addAlgorithm(BuildItinerariesPOI())
        self.addAlgorithm(AddGradeAlgorithm())
        self.addAlgorithm(FormateODmatrix())
        self.addAlgorithm(DecoupeGTFSAlgorithm())
        self.addAlgorithm(BuildGraphGTFSAlgorithm())
        self.addAlgorithm(MergeGTFS())


        
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'mobilityhubplugin'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('Mobility Hub Locator Toolbox')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
