# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterBand,
    QgsProcessingParameterNumber,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterFeatureSink,
    QgsFeature,
    QgsFeatureSink,
    QgsField,
    QgsFields,
    QgsWkbTypes,
    QgsCoordinateTransform,
    QgsProject,
    QgsDistanceArea,
    QgsPointXY,
)


class AddGradeAlgorithm(QgsProcessingAlgorithm):
 
    INPUT = "INPUT"
    DEM = "DEM"
    BAND = "BAND"
    TOLERANCE = "TOLERANCE"
    AS_PERCENT = "AS_PERCENT"
    OUTPUT = "OUTPUT"
 
    def tr(self, string):
        return QCoreApplication.translate("AddGradeAlgorithm", string)
 
    def createInstance(self):
        return AddGradeAlgorithm()
 
    def name(self):
        return "road_network_grades"
 
    def displayName(self):
        return self.tr("Ajouter la pente aux lignes d'un réseau")
 
    def group(self):
        return self.tr("Réseau")
 
    def groupId(self):
        return "reseau"
 
    def shortHelpString(self):
        return self.tr(
            "Calcule la pente de chaque tronçon (arête) d'un réseau linéaire "
            "à partir d'un MNT, en garantissant que deux arêtes partageant un "
            "même nœud utilisent exactement la même altitude à ce nœud."
        )
 
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr("Réseau routier (lignes)"),
                types=[QgsProcessing.TypeVectorLine],
            )
        )
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DEM, self.tr("MNT (raster d'altitude)")
            )
        )
        self.addParameter(
            QgsProcessingParameterBand(
                self.BAND, self.tr("Bande du MNT"), 1, self.DEM
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.TOLERANCE,
                self.tr(
                    "Tolérance de fusion des nœuds (unités de la couche, "
                    "ex: 0.01 = 1cm si projeté en mètres)"
                ),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.01,
                minValue=0.0,
            )
        )
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.AS_PERCENT,
                self.tr("Exprimer la pente en pourcentage (sinon ratio)"),
                defaultValue=True,
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(self.OUTPUT, self.tr("Réseau avec pentes"))
        )
 
    def _endpoints(self, geom):
        """Retourne (premier_sommet, dernier_sommet) en gérant simple/multi lignes."""
        if geom.isMultipart():
            parts = geom.asMultiPolyline()
            parts = [p for p in parts if p]
            if not parts:
                return None, None
            first_pt = parts[0][0]
            last_pt = parts[-1][-1]
        else:
            line = geom.asPolyline()
            if not line:
                return None, None
            first_pt = line[0]
            last_pt = line[-1]
        return QgsPointXY(first_pt), QgsPointXY(last_pt)
 
    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsVectorLayer(parameters, self.INPUT, context)
        dem = self.parameterAsRasterLayer(parameters, self.DEM, context)
        band = self.parameterAsInt(parameters, self.BAND, context)
        tol = self.parameterAsDouble(parameters, self.TOLERANCE, context)
        as_percent = self.parameterAsBool(parameters, self.AS_PERCENT, context)
 
        if tol <= 0:
            tol = 0.01  # évite une division par zéro dans l'arrondi
 
        #Vérification de la cohérence des crs
        transform = None
        if source.crs() != dem.crs():
            transform = QgsCoordinateTransform(
                source.crs(), dem.crs(), QgsProject.instance()
            )
 
        # Pour la longueur "vraie" (ellipsoïdale si CRS géographique)
        distance_area = QgsDistanceArea()
        distance_area.setSourceCrs(source.crs(), QgsProject.instance().transformContext())
        distance_area.setEllipsoid(QgsProject.instance().ellipsoid())
 
        provider = dem.dataProvider()
 
        # ---- Passe 1 : identifier les nœuds uniques (snap par grille) ----
        feedback.pushInfo("Étape 1/3 : identification des nœuds du réseau...")
        node_repr_point = {}  # clé de grille -> point représentatif (CRS du MNT)
        features = list(source.getFeatures())
        total = len(features) or 1
 
        for i, feat in enumerate(features):
            if feedback.isCanceled():
                return {}
            geom = feat.geometry()
            if geom is None or geom.isEmpty():
                continue
            p_start, p_end = self._endpoints(geom)
            if p_start is None:
                continue
            for pt in (p_start, p_end):
                pt_dem = transform.transform(pt) if transform else pt
                key = (round(pt_dem.x() / tol), round(pt_dem.y() / tol))
                if key not in node_repr_point:
                    node_repr_point[key] = pt_dem
            feedback.setProgress(int(30 * i / total))
 
        # ---- échantillonner le MNT une seule fois par nœud ----
        feedback.pushInfo(
            f"Étape 2/3 : échantillonnage du MNT sur {len(node_repr_point)} nœuds uniques..."
        )
        node_elev = {}
        n_nodes = len(node_repr_point) or 1
        for j, (key, pt_dem) in enumerate(node_repr_point.items()):
            if feedback.isCanceled():
                return {}
            val, ok = provider.sample(pt_dem, band)
            node_elev[key] = val if ok and val is not None else None
            feedback.setProgress(30 + int(30 * j / n_nodes))
 
        # ---- Préparation des champs de sortie ----
        out_fields = QgsFields(source.fields())
        for fname, ftype in (
            ("elev_start", QVariant.Double),
            ("elev_end", QVariant.Double),
            #("length_m", QVariant.Double),
            ("grade", QVariant.Double),
            ("grade_abs", QVariant.Double),
        ):
            out_fields.append(QgsField(fname, ftype))
 
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            out_fields,
            source.wkbType(),
            source.crs(),
        )
 
        # ---- calcul de la pente par arête ----
        feedback.pushInfo("Étape 3/3 : calcul de la pente par tronçon...")
        n_missing_dem = 0
        for i, feat in enumerate(features):
            if feedback.isCanceled():
                return {}
            geom = feat.geometry()
            new_feat = QgsFeature(out_fields)
            new_feat.setGeometry(geom)
            attrs = feat.attributes()
 
            elev_start = elev_end = length_m = grade = grade_abs = None
 
            if geom is not None and not geom.isEmpty():
                p_start, p_end = self._endpoints(geom)
                if p_start is not None:
                    pt_start_dem = transform.transform(p_start) if transform else p_start
                    pt_end_dem = transform.transform(p_end) if transform else p_end
                    key_start = (round(pt_start_dem.x() / tol), round(pt_start_dem.y() / tol))
                    key_end = (round(pt_end_dem.x() / tol), round(pt_end_dem.y() / tol))
                    elev_start = node_elev.get(key_start)
                    elev_end = node_elev.get(key_end)
 
                    try:
                        length_m = distance_area.measureLength(geom)
                    except Exception:
                        length_m = geom.length()
 
                    if elev_start is None or elev_end is None:
                        n_missing_dem += 1
                    elif length_m and length_m > 0:
                        grade = (elev_end - elev_start) / length_m
                        if as_percent:
                            grade *= 100.0
                        grade_abs = abs(grade)
 
            new_feat.setAttributes(
                attrs + [elev_start, elev_end, grade, grade_abs]
            )
            sink.addFeature(new_feat, QgsFeatureSink.FastInsert)
            feedback.setProgress(60 + int(40 * i / total))
 
        if n_missing_dem:
            feedback.pushWarning(
                f"{n_missing_dem} tronçon(s) sans altitude valide "
                "(hors emprise du MNT ou NoData)."
            )
 
        return {self.OUTPUT: dest_id}
