# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



# build_graph_algorithm.py
from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessing,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFile,
    QgsVectorLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterEnum,
    QgsProcessingParameterField,
    QgsProcessingOutputString,
    QgsProcessingOutputLayerDefinition,
    QgsProcessingParameterString,
    QgsProcessingParameterFeatureSink,
    QgsFeature, QgsGeometry, QgsFields, QgsField,
    QgsWkbTypes, QgsCoordinateReferenceSystem,
)
from qgis.analysis import QgsVectorLayerDirector
from qgis.PyQt.QtCore import QVariant, QCoreApplication

from .conversions import (qgis_layer_to_gdf, 
                         gdf_geom_to_qgs_wkbtype,
                         gdf_to_qgsfields,
                         write_gdf_to_sink)

#Bibliothèques python
import osmnx as ox
import numpy as np
import pandas as pd
import networkx as nx
import geopandas as gpd
import partridge as ptg
from scipy.spatial import cKDTree
from geopy.distance import distance
from shapely import ops as sops
import pyproj
from shapely.geometry import Point, Polygon, LineString
import shapely
SPEED = {
    'walk': 4 * 1000 / 3600,
    'bike': 15 * 1000 / 3600,
    'transfer': 5 * 1000 / 3600,
    'transit': 22 * 1000 / 3600
}


def compute_speed_from_stop_times(stop_sequence_df, stops_gdf, feedback=None, trip_id=None):
    """
    Calcule la vitesse réelle entre chaque paire d'arrêts
    depuis les horaires GTFS.
    
    Parameters
    ----------
    stop_sequence_df : DataFrame
        stop_times filtré et trié pour un trip_id donné
    stops_gdf : GeoDataFrame
        stops avec colonne geometry
    
    Returns
    -------
    list of dict : [{u, v, speed_kph, travel_time_min, length_m}]
    """
    results = []
    rows = stop_sequence_df.reset_index(drop=True)
    
    for i in range(len(rows) - 1):
        u = rows.iloc[i]
        v = rows.iloc[i + 1]
        
        # Calcul du temps de trajet réel
        dep = (u['departure_time'])  # gère les >24h (service de nuit)
        arr = (v['arrival_time'])
        delta_minutes = (arr - dep) / 60
        
        #feedback.pushInfo(f"Temps avec première méthode : {delta_minutes}")
        
        

        # Calcul de la distance
        pt_u = stops_gdf.loc[stops_gdf.stop_id == u['stop_id'], 'geometry'].values[0]
        pt_v = stops_gdf.loc[stops_gdf.stop_id == v['stop_id'], 'geometry'].values[0]
        if delta_minutes <= 0:
            # Probablement du TAD
            if feedback:
                feedback.pushInfo(f"Départ : {dep} vs Arrivée : {arr}")
            dist_m = distance((pt_u.y, pt_u.x), (pt_v.y, pt_v.x)).m
            delta_minutes = (dist_m / 1000) / 22 * 60  # vitesse par défaut 22 km/h
            if feedback and trip_id:
                feedback.pushInfo(f"[trip {trip_id}] horaire invalide u={u['stop_id']} "
                                   f"v={v['stop_id']}, estimation à {delta_minutes:.1f} min")      
        


        
        results.append({
            'u': u['stop_id'],
            'v': v['stop_id'],
            'travel_time_min': round(delta_minutes, 2)
        })
    return results
    

class BuildGraphGTFSAlgorithm(QgsProcessingAlgorithm):

    INPUT = "INPUT"
    LI_PIETON ="LI_PIETON"
    NO_PIETON ="NO_PIETON"
    SPEED_FIELD = "SPEED_FIELD"
    LIGNES = 'LIGNES'
    NOEUDS = "NOEUDS"
    def __init__(self):
        super().__init__()
    def name(self): return "build_graph_gtfs"
    def displayName(self): return "Construire le graphe réseau à partir d'un zip gtfs"
    def createInstance(self): return BuildGraphGTFSAlgorithm()
    def group(self): return "Réseau"
    def groupId(self): return "reseau"
    def tr(self, string):
        return QCoreApplication.translate('BuildGraphGTFSAlgorithm', string)
    def initAlgorithm(self, config=None):
        
        
        self.addParameter(QgsProcessingParameterFile(self.INPUT, self.tr("Réseau")))
        self.addParameter(QgsProcessingParameterVectorLayer(self.NO_PIETON, 
                                                              "Nœuds du réseau piéton (points)",
                                                              [QgsProcessing.SourceType.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterVectorLayer(self.LI_PIETON, 
                                                              "Lignes du réseau piéton (lignes)",
                                                              [QgsProcessing.SourceType.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterField(self.SPEED_FIELD, 
                                                      self.tr("Colonne vitesse en voiture"), 
                                                      parentLayerParameterName=self.LI_PIETON,
                                                      optional=True))
        self.addParameter(QgsProcessingParameterFeatureSink(self.LIGNES, self.tr("Couche linéaire du graphe")))
        self.addParameter(QgsProcessingParameterFeatureSink(self.NOEUDS, self.tr("Couche des noeuds du graphe")))
    
    
    
    def processAlgorithm(self, parameters, context, feedback):
        zip_path = self.parameterAsFile(parameters, self.INPUT, context)
        li_layer = self.parameterAsVectorLayer(parameters, self.LI_PIETON, context)
        no_layer = self.parameterAsVectorLayer(parameters, self.NO_PIETON, context)
        
        #Construction graphe piéton
        li_crs = li_layer.crs().authid()  
        edges = qgis_layer_to_gdf(li_layer)
        nodes= qgis_layer_to_gdf(no_layer)
        osm_nodes = nodes.set_index("osmid")
        osm_nodes = osm_nodes.to_crs(2154)
        edges = edges.set_index(["u", "v", "key"])
        if not edges.index.is_unique:
            print("Not unique !")
            edges = edges.reset_index()
            edges['key'] = edges.groupby(['u', 'v']).cumcount(ascending = True)
            edges = edges.set_index(["u", "v", "key"])
        G_osm = ox.graph_from_gdfs(osm_nodes, edges) #graphe piéton
        feedback.pushInfo(f"crs des arêtes : {edges.crs}")

        if li_crs != "EPSG:2154":
            G_osm = ox.project_graph(G_osm, to_crs="EPSG:2154")
            feedback.pushInfo(f"Réseau piéton reprojeté de {li_crs} vers EPSG:2154")
        
        # =============================================================================
        #         Création du graphe simple GTFS
        # =============================================================================
        #Load gtfs with partridge
        feed = ptg.load_geo_feed(zip_path, view={})
        # Extract GTFS tables
        stop_times = feed.stop_times
        trips = feed.trips
        stops = feed.stops
        routes = feed.routes
        if hasattr(feed, 'shapes') and feed.shapes is not None and not feed.shapes.empty:
            shapes = feed.shapes
        else:
            feedback.pushInfo("Attention: shapes.txt absent ou vide \n Construction des shapes ")
            #shapes = shape_selon_geom(gtfs)
        

        #feedback.pushInfo(f"dtype stop_sequence: {stop_times['stop_sequence'].dtype}")
        #stop_times['stop_sequence'] = pd.to_numeric(stop_times['stop_sequence'])

        # Initialize a multidirected graph
        G = nx.MultiDiGraph()

        # Add each transit stop as a node in the graph
        for _, row in stops.iterrows():
            G.add_node(row['stop_id'], name=row['stop_name'], x=row['geometry'].x, y=row['geometry'].y)

        # Ensure all shape geometries are LineString
        shapes['geometry'] = shapes['geometry'].apply( lambda geoms: geoms if isinstance(geoms, LineString) else LineString(geoms))
        shapes_liees = shapes.merge(trips, on = "shape_id")
        shapes_liees = shapes_liees.merge(routes, on = "route_id")
        
        shapes = shapes.set_index('shape_id').geometry
        
        # Vérification
        # feedback.pushInfo(f"Trips sans shape_id : {trips['shape_id'].isna().sum()} / {len(trips)}")
        # manquants = trips[~trips['shape_id'].isin(shapes.index)]
        # feedback.pushInfo(f"Trips avec shape_id introuvable dans shapes.txt : {len(manquants)}")

        # Vérification géométrie
        feedback.pushInfo(f"Bounds stops (lon,lat) : {stops.total_bounds}")
        feedback.pushInfo(f"Bounds shapes (lon,lat) : {gpd.GeoSeries(shapes).total_bounds}")
        
        
        # trips_sans_horaire_valide = trips[~trips['trip_id'].isin(
        # stop_times.groupby('trip_id').filter(
        #     lambda g: (pd.to_timedelta(g.sort_values('stop_sequence')['departure_time']).diff().dt.total_seconds() > 0).any()
        # )['trip_id']
        # )]
        # feedback.pushInfo(f"Horaires invalides : {len(trips_sans_horaire_valide)} / {len(trips)} trips concernés")
        
        # Create edges from trips, grouped by shape_id
        for shape_id, group in trips.groupby('shape_id'):
            if shape_id not in shapes.index or shapes[shape_id] is None:
                continue
            geoms = shapes[shape_id]
            #feedback.pushInfo(f"Type de géométrie : {geoms.type}")

            # Take the first trip in the group as representative
            trip_id = group.iloc[0]['trip_id']

            # Get the stop sequence for the trip
            stop_sequence = stop_times[stop_times.trip_id == trip_id].sort_values('stop_sequence')
            stop_id = stop_sequence['stop_id'].tolist()
            
            #Calcul vitesse réelle
            speed_data = compute_speed_from_stop_times(stop_sequence, stops, feedback, trip_id)            
            if not speed_data:
                feedback.pushInfo(f"[shape {shape_id}, trip {trip_id}] Aucun segment valide "
                       f"(stop_sequence dtype={stop_sequence['stop_sequence'].dtype}, "
                       f"n_stops={len(stop_sequence)})")
            
            for seg in speed_data:
                u, v = seg['u'], seg['v']
                # Retrieve the coordinates of the two stops
                point_u = stops.loc[stops.stop_id == u, 'geometry'].values[0]
                point_v = stops.loc[stops.stop_id == v, 'geometry'].values[0]
                #feedback.pushInfo(f"u : {str(point_u)}, v : {str(point_v)}")
                length = distance((point_u.y, point_u.x), (point_v.y, point_v.x)).m
                #On est en 4326 donc distance géodésique


                # Get geometry for the edge
                try:
                    orig = geoms.project(point_u)
                    dest = geoms.project(point_v)
                    low, high = sorted([orig, dest])
                    segment = sops.substring(geoms, low, high, normalized=False)
                    #feedback.pushInfo(f"Type de segment : {str(segment.type)}")
                    if segment.is_empty or segment.length == 0:
                        segment = LineString([point_u, point_v])
                except Exception as e:
                    feedback.pushWarning(f"[shape {shape_id}] projection échouée u={u} v={v}: {e}")
                    segment = LineString([point_u, point_v])
                #length = segment.length
                
                delta_hours = seg['travel_time_min'] / 60
                speed_kph = (length / 1000) / delta_hours if delta_hours > 0 else 22.0
                if not G.has_edge(u, v, key=trip_id):
                    G.add_edge(
                        u, v,
                        trip_id=trip_id,
                        geometry=segment,
                        length=length,
                        mode='transit',
                        speed_kph=speed_kph,     
                        travel_time=seg['travel_time_min']
                    )

            

        # Set the graph's CRS based on the stops' coordinates
        if stops.crs is not None:
            G.graph['crs'] = stops.crs
        else:
            G.graph['crs'] = "EPSG:4326"
        
        transformer = pyproj.Transformer.from_crs("EPSG:4326", "EPSG:2154", always_xy=True).transform
        # Set the graph's CRS to Lambert-93 (EPSG:2154)
        # On reprojette les lignes puis les noeuds
        if G.graph.get('crs') != "EPSG:2154":
            for u, v, k, data in G.edges(keys=True, data=True):
                if 'geometry' in data and data['geometry'] is not None:
                    data['geometry'] = sops.transform(transformer, data['geometry'])
            G = ox.project_graph(G,to_crs = 2154)
            feedback.pushInfo(f"Reprojection en {G.graph['crs']} !")
        
        for u, v, k, data in list(G.edges(keys=True, data=True))[:3]:
            if 'geometry' in data:
                feedback.pushInfo(f"edge geometry bounds: {data['geometry'].bounds}")
                node0 = list(G.nodes(data=True))[0]
                feedback.pushInfo(f"node x,y: {node0[1].get('x')}, {node0[1].get('y')}")
                
        # n_transit = sum(1 for _, _, d in G.edges(data=True) if d.get('mode') == 'transit')
        # feedback.pushInfo(f"Arêtes transit créées avant compose: {n_transit}")
        
        # =============================================================================
        #         Connexion des deux graphes
        # =============================================================================
        zone_etude = osm_nodes.geometry.union_all().convex_hull
        offset = max(G_osm.nodes(), default=-1) + 1
        G_gtfs = nx.relabel_nodes(
            G, {node: offset + i for i, node in enumerate(G.nodes())}, copy=True
            )
        #G_gtfs = nx.relabel_nodes(G, {node: i for i, node in enumerate(G.nodes())}, copy=True)

        # Get OSM node coordinates
        osm_coords = np.array(list(zip(osm_nodes["y"], osm_nodes["x"])))

        # Get GTFS stop coordinates
        gtfs_nodes = [(n, data["x"], data["y"]) for n, data in G_gtfs.nodes(data=True)]
        gtfs_coords = np.array([(y, x) for _, x, y in gtfs_nodes])

        # Build KD-tree for nearest-neighbor search
        tree = cKDTree(osm_coords) #pose pb quand arrêt hors zone

         # Combine OSM and GTFS graphs
        G = nx.compose(G_osm, G_gtfs)
        
        k=1

        # Connect each GTFS stop to its nearest OSM node(s)
        for (stop_id, x, y), (dist, idx) in zip(gtfs_nodes, zip(*tree.query(gtfs_coords, k=k))):
            point_stop = Point(x, y)
            #Vérification distance
            if not zone_etude.contains(point_stop):
                feedback.pushWarning(f"Arrêt {stop_id} ignoré : noeud piéton le plus proche à {dist:.0f} m")

                continue
            osm_node = osm_nodes.iloc[idx].name
            point_u = Point(x,y)
            point_v = Point(osm_nodes.iloc[idx].x, osm_nodes.iloc[idx].y)
            
            #feedback.pushInfo(f"u : {str(point_u)}, v : {str(point_v)}")

            length = shapely.distance(point_u, point_v) #On est en 2154
            travel_time = length / SPEED['transfer'] / 60
            G.add_edge(stop_id, osm_node, mode="transfer", length=length, travel_time=travel_time)
            G.add_edge(osm_node, stop_id, mode="transfer", length=length, travel_time=travel_time)

        # Set the graph's CRS to Lambert-93 (EPSG:2154)
        if G.graph.get('crs') is not None:
            G.graph["crs"] = edges.crs
        
        
        
        
        
        nodes, lines = ox.graph_to_gdfs(G)
        feedback.pushInfo(f"Nombres d'arêtes : {len(lines)}")
        nodes = nodes.reset_index()
        lines = lines.reset_index()
        
        feedback.pushInfo("Conversion en Vector Layer ...")

        crs = li_layer.crs()  # on réutilise le CRS de la couche d'entrée

        # --- Sink lignes ---
        lines_fields = gdf_to_qgsfields(lines)
        lines_wkbtype = gdf_geom_to_qgs_wkbtype(lines)
        (sink_lignes, dest_id_lignes) = self.parameterAsSink(
            parameters, self.LIGNES, context,
            lines_fields, lines_wkbtype, crs
        )
        write_gdf_to_sink(lines, sink_lignes)
    
        # --- Sink noeuds ---
        nodes_fields = gdf_to_qgsfields(nodes)
        nodes_wkbtype = gdf_geom_to_qgs_wkbtype(nodes)
        (sink_noeuds, dest_id_noeuds) = self.parameterAsSink(
            parameters, self.NOEUDS, context,
            nodes_fields, nodes_wkbtype, crs
        )
        write_gdf_to_sink(nodes, sink_noeuds)
        return {self.LIGNES: dest_id_lignes, self.NOEUDS: dest_id_noeuds}
            
            
    