# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessing,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterMultipleLayers,
    QgsProcessingParameterFile,
    QgsProcessingParameterFileDestination,
    QgsVectorLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterEnum,
    QgsProcessingParameterField,
    QgsProcessingOutputString,
    QgsProcessingOutputLayerDefinition,
    QgsProcessingParameterString,
    QgsProcessingParameterFeatureSink,
    QgsFeature, QgsGeometry, QgsFields, QgsField,
    QgsWkbTypes, QgsCoordinateReferenceSystem,
)
from qgis.analysis import QgsVectorLayerDirector
from qgis.PyQt.QtCore import QVariant, QCoreApplication

from mobilityhubplugin.conversions import  seconds_to_hms


import pandas as pd
import zipfile
import partridge as ptg

def load_and_prefix(zip_path, prefix, feedback):
    """Charge un GTFS avec Partridge et préfixe les identifiants clés"""
    feed = ptg.load_feed(zip_path)
    
    # Liste des tables standards GTFS à extraire si elles existent
    tables = ['agency', 'stops', 'routes', 'trips', 'stop_times', 'calendar', 'calendar_dates', 'transfers',"shapes"]
    feed_dfs = {}
    
    for table in tables:
        feedback.pushInfo(f"Analayse de la table {table} ")

        try:
            df = getattr(feed, table).copy()
            if df.empty:
                feedback.pushWarning(f"La table {table} est vide")
                continue
                
            # Colonnes d'identifiants à préfixer pour éviter les doublons entre bus et trains
            id_cols = ['stop_id', 'parent_station', 'trip_id', 'route_id', 'service_id', 'agency_id']
            for col in id_cols:
                if col in df.columns:
                    # On s'assure de ne préfixer que les valeurs non nulles
                    df[col] = df[col].apply(lambda x: f"{prefix}{x}" if pd.notna(x) and x != '' else x)
            
            feed_dfs[table] = df
            feedback.pushInfo(f"La table {table} a été ajoutée")
        except AttributeError:
            feedback.pushWarning(f"La table {table} n'a pas été trouvée dans {zip_path}")
            # La table n'existe pas dans ce flux
            continue
            
    return feed_dfs





class MergeGTFS(QgsProcessingAlgorithm):

    REP_GTFS = "REP_GTFS"
    OUTPUT_ZIP = "OUTPUT_ZIP"
    def __init__(self):
        super().__init__()
    def name(self): return "merge_gtfs"
    def displayName(self): return "Concaténer des réseaux de transports en commun"
    def createInstance(self): return MergeGTFS()
    def group(self): return "Formatage préliminaire"
    def groupId(self): return "formatage"
    def tr(self, string):
        return QCoreApplication.translate('MergeGTFS', string)
    def initAlgorithm(self, config=None):
        
        self.addParameter(
            QgsProcessingParameterMultipleLayers(
                self.REP_GTFS,
                self.tr('Zip GTFS à concaténer'),
                layerType= QgsProcessing.TypeFile
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_ZIP,
                self.tr('Chemin de sortie'),
                fileFilter = "*.zip",
                defaultValue='*.zip',
                optional=False

                
            )
        )
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        
        source = self.parameterAsFileList(parameters, self.REP_GTFS, context)
        #emprise = self.parameterasSource(parameters, self.EMPRISE, context)
        sortie=(self.parameterAsFileOutput(parameters, self.OUTPUT_ZIP, context))
        
        all_feeds_data = []
        liste_tables_trouvees = set()    
        merged_feed ={}
        #Liste des fichiers standards du GTFS à traiter
        
        
        
        for k,zip_path in enumerate(source):
            prefix = f"{k+ 1}00000"
            feedback.pushInfo(str(prefix))
            #feed = ptg.load_feed(zip_path, view={})
            feed_data = load_and_prefix(zip_path, prefix, feedback)

            all_feeds_data.append(feed_data)
            liste_tables_trouvees.update(feed_data.keys())
            feedback.pushInfo(str(liste_tables_trouvees))

        
        for table in liste_tables_trouvees:
            feedback.pushInfo(table)

            dfs_to_concat = []
            for feed_data in all_feeds_data:

                if table in feed_data:
                    dfs_to_concat.append(feed_data[table])
            # Concaténation des lignes des deux DataFrames
            merged_feed[table] = pd.concat(dfs_to_concat, ignore_index=True)
            
        

            
        TIME_COLUMNS = {
            "stop_times": ["arrival_time", "departure_time"],
            "frequencies": ["start_time", "end_time"],
        }
        for table_name, cols in TIME_COLUMNS.items():
            if table_name in merged_feed:
                for col in cols:
                    if col in merged_feed[table_name].columns:
                        merged_feed[table_name][col] = merged_feed[table_name][col].apply(seconds_to_hms)
                        feedback.pushInfo(f"Vérification du type d'heure : {str(merged_feed[table_name][col].head(2))}")
        DATE_COLUMNS = {
            "calendar": ["start_date", "end_date"],
            "calendar_dates": ["date"],
        }
        for table_name, cols in DATE_COLUMNS.items():
            if table_name in merged_feed:
                for col in cols:
                    if col in merged_feed[table_name].columns:
                        s = pd.to_datetime(merged_feed[table_name][col])
                        merged_feed[table_name][col] = s.dt.strftime('%Y%m%d')
       
        #Concaténer et sauvegarder dans le nouveau fichier ZIP
        
        feedback.pushInfo("Ecriture dans le zip...")

        with zipfile.ZipFile(sortie, 'w', zipfile.ZIP_DEFLATED) as out_z:
            feedback.pushInfo(f" Rappel du chemin {sortie}...")

            for table_name, df in merged_feed.items():
                feedback.pushInfo(f" Table en cours de traitement : {table_name}...")

                file_name = f"{table_name}.txt"
                # Conversion du DataFrame en chaîne de caractères CSV
                csv_data = df.to_csv(index=False)
                # Ajout direct dans le ZIP
                out_z.writestr(file_name, csv_data)
                feedback.pushInfo(f" Table traitée : {table_name}...")

            
        feedback.pushInfo(f"Table {file_name} fusionnée avec succès.")
        
        return {'SORTIE': sortie}






