"""
/***************************************************************************
 MobilityHubPlugin
                                 A QGIS plugin
 Ce plugin calcule des zones pertinentes où installer des PEM (méthode développée par Frank et al. (2021))
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterField,
    QgsProcessingParameterFile,
    QgsProcessingParameterEnum,
    QgsProcessingParameterBoolean,
    QgsFeatureSink,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant

from .optimization_model import ProblemData, solve_poi_model
from .conversions import build_poi_problem_data

class LocateHubsPOIAlgorithm(QgsProcessingAlgorithm):
    POP = "POP"
    IDPOP = "IDPOP"
    COLPOP = "COLPOP"
    
    HUBS = "HUBS"
    IDHUB = "IDHUB"
    
    DESTINATION = "DESTINATION"
    IDDEST ="IDDEST"
    POICATEGORY = "POICATEGORY"
    POITRAVEL = "POITRAVEL"
    
    ITINERAIRES= "ITINERAIRES"
    BUDGET = "BUDGET"
    THRESHOLD = "THRESHOLD"
    LISTE = "LISTE"
    ALLOW_CS = "ALLOW_CS"
    OUTPUT = "OUTPUT"
    
    LISTE: list[str] = ["Oui", "Non"]
    def createInstance(self):
        return LocateHubsPOIAlgorithm()

    def name(self):
        return "locate_hubs_poi"

    def displayName(self):
        return "Localiser les hubs (accessibilité POI)"

    def group(self):
        return "Localisateur de Hubs"

    def groupId(self):
        return "mobility_hub"

    def initAlgorithm(self, config=None):
        
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.POP, "Nœuds de population (points)",
                [QgsProcessing.TypeVectorPoint]))
        self.addParameter(
            QgsProcessingParameterField(
                self.COLPOP, 
                "Colonne id pour la couche de population",
                parentLayerParameterName=self.POP))
        self.addParameter(
            QgsProcessingParameterField(
                self.IDPOP, 
                "Colonne population pour la couche de population",
                parentLayerParameterName=self.POP))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.HUBS, 
                "Hubs candidats (points)",
                [QgsProcessing.TypeVectorPoint]))
        self.addParameter(
            QgsProcessingParameterField(
                self.IDHUB, 
                "Colonne id pour la couche des hubs",
                parentLayerParameterName=self.HUBS))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.DESTINATION, 
                "Points d'intérêt (points, avec champ 'category')",
                [QgsProcessing.TypeVectorPoint]))
        self.addParameter(
            QgsProcessingParameterField(self.IDDEST, 
                                        "Colonne id pour la couche de destination",
                                        parentLayerParameterName=self.DESTINATION,
                                              ))
        self.addParameter(
            QgsProcessingParameterField(self.POICATEGORY,
                                        "Colonne de catégorie des services",
                                        parentLayerParameterName = self.DESTINATION))
        self.addParameter(QgsProcessingParameterField(self.POITRAVEL, 
                                                       "Colonne de seuil de temps de trajet (min)",
                                                       parentLayerParameterName = self.DESTINATION))
        self.addParameter(
            QgsProcessingParameterFile(self.ITINERAIRES, 
                                       "Itinéraires potentiels"))
        self.addParameter(
            QgsProcessingParameterNumber(
                self.BUDGET, "Budget (€)", defaultValue=150000))
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.ALLOW_CS, "Autopartage possible", defaultValue=False))
        
        # self.addParameter(QgsProcessingParameterEnum(self.ALLOW_CS,
        #                                          "Direction par défaut",
        #                                          options =self.LISTE,
        #                                          allowMultiple=False,
        #                                          optional = True,
        #                                          defaultValue= self.LISTE.index("Non")))
        
        self.addParameter(QgsProcessingParameterFeatureSink(self.OUTPUT, 
                                                            "Hubs sélectionnés"))

    def processAlgorithm(self, parameters, context, feedback):
        nodes_src = self.parameterAsVectorLayer(parameters, self.POP, context)#QgsProcessingFeatureSource
        hubs_src = self.parameterAsVectorLayer(parameters, self.HUBS, context)#QgsProcessingFeatureSource
        pois_src = self.parameterAsVectorLayer(parameters, self.DESTINATION, context)#QgsProcessingFeatureSource
        itineraries_src = self.parameterAsSource(parameters, self.ITINERAIRES, context)
        budget = self.parameterAsDouble(parameters, self.BUDGET, context)#float
        category = self.parameterAsString(parameters, self.POICATEGORY, context)
        colonne_travel = self.parameterAsString(parameters, self.POITRAVEL, context)
        allow_unimodal_cs = self.parameterAsBool(parameters, self.ALLOW_CS, context)


        node_id = self.parameterAsString(parameters, self.COLPOP, context)
        hub_id = self.parameterAsString(parameters, self.IDHUB, context)
        dest_id = self.parameterAsString(parameters, self.IDDEST, context)

        feedback.pushInfo(category)
        idx = pois_src.fields().indexFromName(category)
        idx_travel = pois_src.fields().indexFromName(colonne_travel)

        #feedback.pushInfo(str(idx))
        categories = set()
        dict_travel = {}
        
        for feat in pois_src.getFeatures():
            cat = feat[idx]
            travel = feat[idx_travel]
            if isinstance(travel, QVariant):
                travel = 0.0 if travel.isNull() else travel.value()
            #feedback.pushInfo(str(cat))
            categories.add(str(cat))
            if cat not in dict_travel.keys():
                dict_travel[str(cat)] = float(travel)
                
        print(dict_travel)
            


        feedback.pushInfo("Construction des itinéraires potentiels (routage + élimination des dominés)...")
        
        #modes : dans hubs_required 
        data = build_poi_problem_data(feedback,
            nodes_src, hubs_src, itineraries_src,pois_src,
            poi_categories=categories,
            travel_time_threshold=dict_travel,
            node_id_field = node_id,
            hub_id_field = hub_id,
            dest_id_field = dest_id,

            fixed_cost_hub=1000.0,
            fixed_cost_mode={"bs": 300.0, "cs": 7500.0, "pt": 0.0},
            budget=budget,
        )
        feedback.pushInfo(f"Modes détectés : {data.modes}")


        feedback.pushInfo(f"{len(data.itineraries)} itinéraires potentiels générés. Résolution du MIP...")
        result = solve_poi_model(feedback,data, time_limit_s=300, allow_unimodal_cs=allow_unimodal_cs)
        feedback.pushInfo(f"Statut : {result['status']} — accessibilité obtenue : {result['objective']:.3f}")

        fields = QgsFields()
        fields.append(QgsField("hub_id", QVariant.String))
        fields.append(QgsField("mode", QVariant.String))

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context, fields, QgsWkbTypes.Point, hubs_src.sourceCrs()
        )

        hub_features = {f"hub_{f['fid']}": f for f in hubs_src.getFeatures()}
        node_features = {f"pop_{f['code_insee']}": f for f in nodes_src.getFeatures()}
        hub_features.update(node_features)        
        for (hub_id, mode) in result["hubs"]:
            src_feat = hub_features.get(hub_id)
            if src_feat is None:
                continue
            out_feat = QgsFeature(fields)
            out_feat.setGeometry(src_feat.geometry())
            out_feat.setAttributes([hub_id, mode])
            sink.addFeature(out_feat, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}
